//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class BreakingWavesParameters : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public BreakingWavesParameters(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(BreakingWavesParameters obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(BreakingWavesParameters obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~BreakingWavesParameters() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_BreakingWavesParameters(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public BreakingWavesParameters() : this(TritonEnvironmentPINVOKE.new_BreakingWavesParameters(), true) {
  }

  public void SetSteepness(float pSteepness) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetSteepness(swigCPtr, pSteepness);
  }

  public void SetWavelength(float pWavelength) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetWavelength(swigCPtr, pWavelength);
  }

  public void SetWavelengthVariance(float pWavelengthVariance) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetWavelengthVariance(swigCPtr, pWavelengthVariance);
  }

  public void SetWaveDirection(Vector3 pDirection) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetWaveDirection(swigCPtr, Vector3.getCPtr(pDirection));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetAutoWaveDirection(bool on) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetAutoWaveDirection(swigCPtr, on);
  }

  public void SetAmplitude(float pAmplitude) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetAmplitude(swigCPtr, pAmplitude);
  }

  public void SetSurgeDepth(float pSurgeDepth) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetSurgeDepth(swigCPtr, pSurgeDepth);
  }

  public void SetSteepnessVariance(float pSteepnessVariance) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetSteepnessVariance(swigCPtr, pSteepnessVariance);
  }

  public void SetDepthFalloff(float pFalloff) {
    TritonEnvironmentPINVOKE.BreakingWavesParameters_SetDepthFalloff(swigCPtr, pFalloff);
  }

  public float GetSteepness() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetSteepness(swigCPtr);
    return ret;
  }

  public float GetWavelength() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetWavelength(swigCPtr);
    return ret;
  }

  public float GetWavelengthVariance() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetWavelengthVariance(swigCPtr);
    return ret;
  }

  public Vector3 GetWaveDirection() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.BreakingWavesParameters_GetWaveDirection(swigCPtr), false);
    return ret;
  }

  public float GetAmplitude() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetAmplitude(swigCPtr);
    return ret;
  }

  public float GetSurgeDepth() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetSurgeDepth(swigCPtr);
    return ret;
  }

  public float GetSteepnessVariance() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetSteepnessVariance(swigCPtr);
    return ret;
  }

  public float GetPhaseConstant() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetPhaseConstant(swigCPtr);
    return ret;
  }

  public float GetExpK() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetExpK(swigCPtr);
    return ret;
  }

  public float GetSpeed() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetSpeed(swigCPtr);
    return ret;
  }

  public bool GetAutoWaveDirection() {
    bool ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetAutoWaveDirection(swigCPtr);
    return ret;
  }

  public float GetDepthFalloff() {
    float ret = TritonEnvironmentPINVOKE.BreakingWavesParameters_GetDepthFalloff(swigCPtr);
    return ret;
  }

}

}
