//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Camera : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Camera(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Camera obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Camera obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Camera() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonCameraPINVOKE.delete_Camera(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Camera(CoordinateSystem cs) : this(TritonCameraPINVOKE.new_Camera((int)cs), true) {
  }

  public void SetCameraMatrix(SWIGTYPE_p_double m, SWIGTYPE_p_double explicitCameraPosition) {
    TritonCameraPINVOKE.Camera_SetCameraMatrix__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(m), SWIGTYPE_p_double.getCPtr(explicitCameraPosition));
  }

  public void SetCameraMatrix(SWIGTYPE_p_double m) {
    TritonCameraPINVOKE.Camera_SetCameraMatrix__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(m));
  }

  public void SetProjectionMatrix(SWIGTYPE_p_double p) {
    TritonCameraPINVOKE.Camera_SetProjectionMatrix(swigCPtr, SWIGTYPE_p_double.getCPtr(p));
  }

  public SWIGTYPE_p_double GetCameraMatrix() {
    global::System.IntPtr cPtr = TritonCameraPINVOKE.Camera_GetCameraMatrix(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double GetProjectionMatrix() {
    global::System.IntPtr cPtr = TritonCameraPINVOKE.Camera_GetProjectionMatrix(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double GetCameraPosition() {
    global::System.IntPtr cPtr = TritonCameraPINVOKE.Camera_GetCameraPosition(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public Vector3 GetUpVector() {
    Vector3 ret = new Vector3(TritonCameraPINVOKE.Camera_GetUpVector(swigCPtr), true);
    return ret;
  }

  public Vector3 GetRightVector() {
    Vector3 ret = new Vector3(TritonCameraPINVOKE.Camera_GetRightVector(swigCPtr), true);
    return ret;
  }

  public CoordinateSystem GetCoordinateSystem() {
    CoordinateSystem ret = (CoordinateSystem)TritonCameraPINVOKE.Camera_GetCoordinateSystem(swigCPtr);
    return ret;
  }

  public bool CullSphere(Vector3 position, double radius) {
    bool ret = TritonCameraPINVOKE.Camera_CullSphere(swigCPtr, Vector3.getCPtr(position), radius);
    if (TritonCameraPINVOKE.SWIGPendingException.Pending) throw TritonCameraPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool CullOrientedBoundingBox(SWIGTYPE_p_Triton__OrientedBoundingBox obb) {
    bool ret = TritonCameraPINVOKE.Camera_CullOrientedBoundingBox(swigCPtr, SWIGTYPE_p_Triton__OrientedBoundingBox.getCPtr(obb));
    if (TritonCameraPINVOKE.SWIGPendingException.Pending) throw TritonCameraPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsGeocentric() {
    bool ret = TritonCameraPINVOKE.Camera_IsGeocentric(swigCPtr);
    return ret;
  }

  public void SetName(string name) {
    TritonCameraPINVOKE.Camera_SetName(swigCPtr, name);
  }

  public string GetName() {
    string ret = TritonCameraPINVOKE.Camera_GetName(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_Triton__signal1T_Triton__Camera_const_p_t signal_CameraDestroyed {
    set {
      TritonCameraPINVOKE.Camera_signal_CameraDestroyed_set(swigCPtr, SWIGTYPE_p_Triton__signal1T_Triton__Camera_const_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonCameraPINVOKE.Camera_signal_CameraDestroyed_get(swigCPtr);
      SWIGTYPE_p_Triton__signal1T_Triton__Camera_const_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__signal1T_Triton__Camera_const_p_t(cPtr, false);
      return ret;
    } 
  }

  public void SetViewport(int x, int y, int width, int height) {
    TritonCameraPINVOKE.Camera_SetViewport(swigCPtr, x, y, width, height);
  }

  public bool GetViewport(SWIGTYPE_p_int x, SWIGTYPE_p_int y, SWIGTYPE_p_int width, SWIGTYPE_p_int height) {
    bool ret = TritonCameraPINVOKE.Camera_GetViewport(swigCPtr, SWIGTYPE_p_int.getCPtr(x), SWIGTYPE_p_int.getCPtr(y), SWIGTYPE_p_int.getCPtr(width), SWIGTYPE_p_int.getCPtr(height));
    if (TritonCameraPINVOKE.SWIGPendingException.Pending) throw TritonCameraPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRenderTarget(System.IntPtr target) {
    TritonCameraPINVOKE.Camera_SetRenderTarget(swigCPtr, target);
  }

  public System.IntPtr GetRenderTarget() {
     return TritonCameraPINVOKE.Camera_GetRenderTarget(swigCPtr);
   }

}

}
