//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public enum EnvironmentError {
  SUCCEEDED = 0,
  NO_CONFIG_FOUND,
  NULL_RESOURCE_LOADER,
  NO_DEVICE,
  NO_CONTEXT
}

}
