//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Environment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Environment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Environment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Environment obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Environment() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Environment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Environment() : this(TritonEnvironmentPINVOKE.new_Environment(), true) {
  }

  public EnvironmentError Initialize(CoordinateSystem cs, Renderer ren, ResourceLoader rl, System.IntPtr device, bool hdr) {
    EnvironmentError ret = (EnvironmentError)TritonEnvironmentPINVOKE.Environment_Initialize__SWIG_0(swigCPtr, (int)cs, (int)ren, ResourceLoader.getCPtr(rl), device, hdr);
    return ret;
  }

  public EnvironmentError Initialize(CoordinateSystem cs, Renderer ren, ResourceLoader rl, System.IntPtr device) {
    EnvironmentError ret = (EnvironmentError)TritonEnvironmentPINVOKE.Environment_Initialize__SWIG_1(swigCPtr, (int)cs, (int)ren, ResourceLoader.getCPtr(rl), device);
    return ret;
  }

  public EnvironmentError Initialize(CoordinateSystem cs, Renderer ren, ResourceLoader rl) {
    EnvironmentError ret = (EnvironmentError)TritonEnvironmentPINVOKE.Environment_Initialize__SWIG_2(swigCPtr, (int)cs, (int)ren, ResourceLoader.getCPtr(rl));
    return ret;
  }

  public void SetLicenseCode(string userName, string registrationCode) {
    TritonEnvironmentPINVOKE.Environment_SetLicenseCode(swigCPtr, userName, registrationCode);
  }

  public ResourceLoader GetResourceLoader() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_GetResourceLoader(swigCPtr);
    ResourceLoader ret = (cPtr == global::System.IntPtr.Zero) ? null : new ResourceLoader(cPtr, false);
    return ret;
  }

  public System.IntPtr GetDevice() {
     return TritonEnvironmentPINVOKE.Environment_GetDevice(swigCPtr);
   }

  public void SetDirectionalLight(Vector3 direction, Vector3 color) {
    TritonEnvironmentPINVOKE.Environment_SetDirectionalLight(swigCPtr, Vector3.getCPtr(direction), Vector3.getCPtr(color));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetAmbientLight(Vector3 color) {
    TritonEnvironmentPINVOKE.Environment_SetAmbientLight(swigCPtr, Vector3.getCPtr(color));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetLightDirection() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Environment_GetLightDirection(swigCPtr), false);
    return ret;
  }

  public Vector3 GetDirectionalLightColor() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Environment_GetDirectionalLightColor(swigCPtr), false);
    return ret;
  }

  public Vector3 GetAmbientLightColor() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Environment_GetAmbientLightColor(swigCPtr), false);
    return ret;
  }

  public void SetEnvironmentMap(System.IntPtr cubeMap, Matrix3 textureMatrix) {
    TritonEnvironmentPINVOKE.Environment_SetEnvironmentMap__SWIG_0(swigCPtr, cubeMap, Matrix3.getCPtr(textureMatrix));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetEnvironmentMap(System.IntPtr cubeMap) {
    TritonEnvironmentPINVOKE.Environment_SetEnvironmentMap__SWIG_1(swigCPtr, cubeMap);
  }

  public System.IntPtr GetEnvironmentMap() {
     return TritonEnvironmentPINVOKE.Environment_GetEnvironmentMap(swigCPtr);
   }

  public Matrix3 GetEnvironmentMapMatrix() {
    Matrix3 ret = new Matrix3(TritonEnvironmentPINVOKE.Environment_GetEnvironmentMapMatrix(swigCPtr), true);
    return ret;
  }

  public void SetHeightMap(System.IntPtr pHeightMap, Matrix4 worldToTextureCoords, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    TritonEnvironmentPINVOKE.Environment_SetHeightMap__SWIG_0(swigCPtr, pHeightMap, Matrix4.getCPtr(worldToTextureCoords), context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetHeightMap(System.IntPtr pHeightMap, Matrix4 worldToTextureCoords, System.IntPtr context) {
    TritonEnvironmentPINVOKE.Environment_SetHeightMap__SWIG_1(swigCPtr, pHeightMap, Matrix4.getCPtr(worldToTextureCoords), context);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetHeightMap(System.IntPtr pHeightMap, Matrix4 worldToTextureCoords) {
    TritonEnvironmentPINVOKE.Environment_SetHeightMap__SWIG_2(swigCPtr, pHeightMap, Matrix4.getCPtr(worldToTextureCoords));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public System.IntPtr GetHeightMap(SWIGTYPE_p_Triton__Camera camera) {
     return TritonEnvironmentPINVOKE.Environment_GetHeightMap__SWIG_0(swigCPtr, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
   }

  public System.IntPtr GetHeightMap() {
     return TritonEnvironmentPINVOKE.Environment_GetHeightMap__SWIG_1(swigCPtr);
   }

  public Matrix4 GetHeightMapMatrix(SWIGTYPE_p_Triton__Camera camera) {
    Matrix4 ret = new Matrix4(TritonEnvironmentPINVOKE.Environment_GetHeightMapMatrix__SWIG_0(swigCPtr, SWIGTYPE_p_Triton__Camera.getCPtr(camera)), true);
    return ret;
  }

  public Matrix4 GetHeightMapMatrix() {
    Matrix4 ret = new Matrix4(TritonEnvironmentPINVOKE.Environment_GetHeightMapMatrix__SWIG_1(swigCPtr), true);
    return ret;
  }

  public void SetHeightMapRange(float _range) {
    TritonEnvironmentPINVOKE.Environment_SetHeightMapRange(swigCPtr, _range);
  }

  public void SetHeightMapOffset(float _offset) {
    TritonEnvironmentPINVOKE.Environment_SetHeightMapOffset(swigCPtr, _offset);
  }

  public float GetHeightMapRange() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetHeightMapRange(swigCPtr);
    return ret;
  }

  public float GetHeightMapOffset() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetHeightMapOffset(swigCPtr);
    return ret;
  }

  public void SetDepthMap(System.IntPtr pDepthMap) {
    TritonEnvironmentPINVOKE.Environment_SetDepthMap(swigCPtr, pDepthMap);
  }

  public System.IntPtr GetDepthMap() {
     return TritonEnvironmentPINVOKE.Environment_GetDepthMap(swigCPtr);
   }

  public void SetBreakingWavesParameters(BreakingWavesParameters params_) {
    TritonEnvironmentPINVOKE.Environment_SetBreakingWavesParameters(swigCPtr, BreakingWavesParameters.getCPtr(params_));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public BreakingWavesParameters GetBreakingWavesParameters() {
    BreakingWavesParameters ret = new BreakingWavesParameters(TritonEnvironmentPINVOKE.Environment_GetBreakingWavesParameters(swigCPtr), false);
    return ret;
  }

  public void SetPlanarReflectionMap(System.IntPtr textureMap, Matrix3 textureMatrix, float normalDisplacementScale) {
    TritonEnvironmentPINVOKE.Environment_SetPlanarReflectionMap__SWIG_0(swigCPtr, textureMap, Matrix3.getCPtr(textureMatrix), normalDisplacementScale);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPlanarReflectionMap(System.IntPtr textureMap, Matrix3 textureMatrix) {
    TritonEnvironmentPINVOKE.Environment_SetPlanarReflectionMap__SWIG_1(swigCPtr, textureMap, Matrix3.getCPtr(textureMatrix));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public System.IntPtr GetPlanarReflectionMap() {
     return TritonEnvironmentPINVOKE.Environment_GetPlanarReflectionMap(swigCPtr);
   }

  public Matrix3 GetPlanarReflectionMapMatrix() {
    Matrix3 ret = new Matrix3(TritonEnvironmentPINVOKE.Environment_GetPlanarReflectionMapMatrix(swigCPtr), true);
    return ret;
  }

  public float GetPlanarReflectionDisplacementScale() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetPlanarReflectionDisplacementScale(swigCPtr);
    return ret;
  }

  public void SimulateSeaState(double beaufortScale, double windDirection, bool leftHanded) {
    TritonEnvironmentPINVOKE.Environment_SimulateSeaState__SWIG_0(swigCPtr, beaufortScale, windDirection, leftHanded);
  }

  public void SimulateSeaState(double beaufortScale, double windDirection) {
    TritonEnvironmentPINVOKE.Environment_SimulateSeaState__SWIG_1(swigCPtr, beaufortScale, windDirection);
  }

  public void AddWindFetch(WindFetch fetch, bool leftHanded) {
    TritonEnvironmentPINVOKE.Environment_AddWindFetch__SWIG_0(swigCPtr, WindFetch.getCPtr(fetch), leftHanded);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddWindFetch(WindFetch fetch) {
    TritonEnvironmentPINVOKE.Environment_AddWindFetch__SWIG_1(swigCPtr, WindFetch.getCPtr(fetch));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearWindFetches() {
    TritonEnvironmentPINVOKE.Environment_ClearWindFetches(swigCPtr);
  }

  public void AddSwell(float waveLength, float waveHeight, float direction, float phase, bool leftHanded) {
    TritonEnvironmentPINVOKE.Environment_AddSwell__SWIG_0(swigCPtr, waveLength, waveHeight, direction, phase, leftHanded);
  }

  public void AddSwell(float waveLength, float waveHeight, float direction, float phase) {
    TritonEnvironmentPINVOKE.Environment_AddSwell__SWIG_1(swigCPtr, waveLength, waveHeight, direction, phase);
  }

  public void AddSwell(float waveLength, float waveHeight, float direction) {
    TritonEnvironmentPINVOKE.Environment_AddSwell__SWIG_2(swigCPtr, waveLength, waveHeight, direction);
  }

  public void ClearSwells() {
    TritonEnvironmentPINVOKE.Environment_ClearSwells(swigCPtr);
  }

  public void SetDouglasSeaScale(int seaState, float windWaveDirection, int swellState, float swellDirection, bool leftHanded) {
    TritonEnvironmentPINVOKE.Environment_SetDouglasSeaScale__SWIG_0(swigCPtr, seaState, windWaveDirection, swellState, swellDirection, leftHanded);
  }

  public void SetDouglasSeaScale(int seaState, float windWaveDirection, int swellState, float swellDirection) {
    TritonEnvironmentPINVOKE.Environment_SetDouglasSeaScale__SWIG_1(swigCPtr, seaState, windWaveDirection, swellState, swellDirection);
  }

  public void GetWind(Vector3 pos, SWIGTYPE_p_double windSpeed, SWIGTYPE_p_double windDirection, SWIGTYPE_p_double fetchLength) {
    TritonEnvironmentPINVOKE.Environment_GetWind(swigCPtr, Vector3.getCPtr(pos), SWIGTYPE_p_double.getCPtr(windSpeed), SWIGTYPE_p_double.getCPtr(windDirection), SWIGTYPE_p_double.getCPtr(fetchLength));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetSeaLevel(double altitudeMSL) {
    TritonEnvironmentPINVOKE.Environment_SetSeaLevel(swigCPtr, altitudeMSL);
  }

  public double GetSeaLevel() {
    double ret = TritonEnvironmentPINVOKE.Environment_GetSeaLevel(swigCPtr);
    return ret;
  }

  public void SetAboveWaterVisibility(double visibility, Vector3 fogColor) {
    TritonEnvironmentPINVOKE.Environment_SetAboveWaterVisibility(swigCPtr, visibility, Vector3.getCPtr(fogColor));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetAboveWaterVisibility(SWIGTYPE_p_double visibility, Vector3 fogColor) {
    TritonEnvironmentPINVOKE.Environment_GetAboveWaterVisibility(swigCPtr, SWIGTYPE_p_double.getCPtr(visibility), Vector3.getCPtr(fogColor));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetBelowWaterVisibility(double visibility, Vector3 fogColor) {
    TritonEnvironmentPINVOKE.Environment_SetBelowWaterVisibility(swigCPtr, visibility, Vector3.getCPtr(fogColor));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetBelowWaterVisibility(SWIGTYPE_p_double visibility, Vector3 fogColor) {
    TritonEnvironmentPINVOKE.Environment_GetBelowWaterVisibility(swigCPtr, SWIGTYPE_p_double.getCPtr(visibility), Vector3.getCPtr(fogColor));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetWaveBlendDepth(double depth) {
    TritonEnvironmentPINVOKE.Environment_SetWaveBlendDepth(swigCPtr, depth);
  }

  public double GetWaveBlendDepth() {
    double ret = TritonEnvironmentPINVOKE.Environment_GetWaveBlendDepth(swigCPtr);
    return ret;
  }

  public void SetSunIntensity(float intensity) {
    TritonEnvironmentPINVOKE.Environment_SetSunIntensity(swigCPtr, intensity);
  }

  public float GetSunIntensity() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetSunIntensity(swigCPtr);
    return ret;
  }

  public void SetWorldUnits(double worldUnits) {
    TritonEnvironmentPINVOKE.Environment_SetWorldUnits(swigCPtr, worldUnits);
  }

  public double GetWorldUnits() {
    double ret = TritonEnvironmentPINVOKE.Environment_GetWorldUnits(swigCPtr);
    return ret;
  }

  public CoordinateSystem GetCoordinateSystem() {
    CoordinateSystem ret = (CoordinateSystem)TritonEnvironmentPINVOKE.Environment_GetCoordinateSystem(swigCPtr);
    return ret;
  }

  public bool IsGeocentric() {
    bool ret = TritonEnvironmentPINVOKE.Environment_IsGeocentric(swigCPtr);
    return ret;
  }

  public Renderer GetRenderer() {
    Renderer ret = (Renderer)TritonEnvironmentPINVOKE.Environment_GetRenderer(swigCPtr);
    return ret;
  }

  public bool IsOpenGL() {
    bool ret = TritonEnvironmentPINVOKE.Environment_IsOpenGL(swigCPtr);
    return ret;
  }

  public bool IsDirectX() {
    bool ret = TritonEnvironmentPINVOKE.Environment_IsDirectX(swigCPtr);
    return ret;
  }

  public void SetCameraMatrix(SWIGTYPE_p_double m, SWIGTYPE_p_double explicitCameraPosition) {
    TritonEnvironmentPINVOKE.Environment_SetCameraMatrix__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(m), SWIGTYPE_p_double.getCPtr(explicitCameraPosition));
  }

  public void SetCameraMatrix(SWIGTYPE_p_double m) {
    TritonEnvironmentPINVOKE.Environment_SetCameraMatrix__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(m));
  }

  public void SetProjectionMatrix(SWIGTYPE_p_double p) {
    TritonEnvironmentPINVOKE.Environment_SetProjectionMatrix(swigCPtr, SWIGTYPE_p_double.getCPtr(p));
  }

  public void SetViewport(int x, int y, int width, int height) {
    TritonEnvironmentPINVOKE.Environment_SetViewport(swigCPtr, x, y, width, height);
  }

  public void SetZoomLevel(float zoom) {
    TritonEnvironmentPINVOKE.Environment_SetZoomLevel(swigCPtr, zoom);
  }

  public float GetZoomLevel() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetZoomLevel(swigCPtr);
    return ret;
  }

  public void SetUserDefinedVertString(string userDefinedString) {
    TritonEnvironmentPINVOKE.Environment_SetUserDefinedVertString(swigCPtr, userDefinedString);
  }

  public void SetUserDefinedFragString(string userDefinedString) {
    TritonEnvironmentPINVOKE.Environment_SetUserDefinedFragString(swigCPtr, userDefinedString);
  }

  public string GetUserDefinedVertString() {
    string ret = TritonEnvironmentPINVOKE.Environment_GetUserDefinedVertString(swigCPtr);
    return ret;
  }

  public string GetUserDefinedFragString() {
    string ret = TritonEnvironmentPINVOKE.Environment_GetUserDefinedFragString(swigCPtr);
    return ret;
  }

  public bool GetViewport(SWIGTYPE_p_int x, SWIGTYPE_p_int y, SWIGTYPE_p_int width, SWIGTYPE_p_int height) {
    bool ret = TritonEnvironmentPINVOKE.Environment_GetViewport(swigCPtr, SWIGTYPE_p_int.getCPtr(x), SWIGTYPE_p_int.getCPtr(y), SWIGTYPE_p_int.getCPtr(width), SWIGTYPE_p_int.getCPtr(height));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Triton__Camera GetCamera() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_GetCamera__SWIG_0(swigCPtr);
    SWIGTYPE_p_Triton__Camera ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__Camera(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_Triton__Camera CreateCamera() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_CreateCamera(swigCPtr);
    SWIGTYPE_p_Triton__Camera ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__Camera(cPtr, false);
    return ret;
  }

  public void DestroyCamera(SWIGTYPE_p_Triton__Camera camera) {
    TritonEnvironmentPINVOKE.Environment_DestroyCamera(swigCPtr, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
  }

  public SWIGTYPE_p_double GetCameraMatrix() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_GetCameraMatrix(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double GetProjectionMatrix() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_GetProjectionMatrix(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double GetCameraPosition() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_GetCameraPosition(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public Vector3 GetUpVector() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Environment_GetUpVector(swigCPtr), true);
    return ret;
  }

  public Vector3 GetRightVector() {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Environment_GetRightVector(swigCPtr), true);
    return ret;
  }

  public void SetConfigOption(string key, string value) {
    TritonEnvironmentPINVOKE.Environment_SetConfigOption(swigCPtr, key, value);
  }

  public string GetConfigOption(string key) {
    string ret = TritonEnvironmentPINVOKE.Environment_GetConfigOption(swigCPtr, key);
    return ret;
  }

  public bool CullSphere(Vector3 position, double radius) {
    bool ret = TritonEnvironmentPINVOKE.Environment_CullSphere(swigCPtr, Vector3.getCPtr(position), radius);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool CullOrientedBoundingBox(SWIGTYPE_p_OrientedBoundingBox obb) {
    bool ret = TritonEnvironmentPINVOKE.Environment_CullOrientedBoundingBox(swigCPtr, SWIGTYPE_p_OrientedBoundingBox.getCPtr(obb));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHDREnabled() {
    bool ret = TritonEnvironmentPINVOKE.Environment_GetHDREnabled(swigCPtr);
    return ret;
  }

  public void EnableOpenMP(bool enabled) {
    TritonEnvironmentPINVOKE.Environment_EnableOpenMP(swigCPtr, enabled);
  }

  public bool GetOpenMPEnabled() {
    bool ret = TritonEnvironmentPINVOKE.Environment_GetOpenMPEnabled(swigCPtr);
    return ret;
  }

  public float GetMaximumWaveHeight() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetMaximumWaveHeight(swigCPtr);
    return ret;
  }

  public void SetCurrent(Vector3 direction, double speed) {
    TritonEnvironmentPINVOKE.Environment_SetCurrent(swigCPtr, Vector3.getCPtr(direction), speed);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetCurrent(Vector3 direction, SWIGTYPE_p_double speed) {
    TritonEnvironmentPINVOKE.Environment_GetCurrent(swigCPtr, Vector3.getCPtr(direction), SWIGTYPE_p_double.getCPtr(speed));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetWaterTransparency(float t) {
    TritonEnvironmentPINVOKE.Environment_SetWaterTransparency(swigCPtr, t);
  }

  public float GetWaterTransparency() {
    float ret = TritonEnvironmentPINVOKE.Environment_GetWaterTransparency(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_Triton__Stream CreateOpenGLStream() {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Environment_CreateOpenGLStream(swigCPtr);
    SWIGTYPE_p_Triton__Stream ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__Stream(cPtr, false);
    return ret;
  }

  public void DestroyOpenGLStream(SWIGTYPE_p_Triton__Stream stream) {
    TritonEnvironmentPINVOKE.Environment_DestroyOpenGLStream(swigCPtr, SWIGTYPE_p_Triton__Stream.getCPtr(stream));
  }

  public void ExecuteOpenGLStream(SWIGTYPE_p_Triton__Stream stream) {
    TritonEnvironmentPINVOKE.Environment_ExecuteOpenGLStream(swigCPtr, SWIGTYPE_p_Triton__Stream.getCPtr(stream));
  }

  public void ResetOpenGLStream(SWIGTYPE_p_Triton__Stream stream) {
    TritonEnvironmentPINVOKE.Environment_ResetOpenGLStream(swigCPtr, SWIGTYPE_p_Triton__Stream.getCPtr(stream));
  }

}

}
