//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class HeightMapContainer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public HeightMapContainer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(HeightMapContainer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(HeightMapContainer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~HeightMapContainer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_HeightMapContainer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public HeightMapContainer() : this(TritonEnvironmentPINVOKE.new_HeightMapContainer(), true) {
  }

  public System.IntPtr heightMap {
    set {
      TritonEnvironmentPINVOKE.HeightMapContainer_heightMap_set(swigCPtr, value);
    } 
    get {
      SWIGTYPE_p_TextureHandle ret = new SWIGTYPE_p_TextureHandle(TritonEnvironmentPINVOKE.HeightMapContainer_heightMap_get(swigCPtr), true);
      return ret;
    } 
  }

  public Matrix4 heightMapMatrix {
    set {
      TritonEnvironmentPINVOKE.HeightMapContainer_heightMapMatrix_set(swigCPtr, Matrix4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.HeightMapContainer_heightMapMatrix_get(swigCPtr);
      Matrix4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Matrix4(cPtr, false);
      return ret;
    } 
  }

}

}
