//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Impact : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Impact(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Impact obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Impact obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Impact() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonImpactPINVOKE.delete_Impact(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Impact(Ocean pOcean, double pImpactorDiameter, double pMass, bool pSprayEffects, double pSprayScale) : this(TritonImpactPINVOKE.new_Impact__SWIG_0(Ocean.getCPtr(pOcean), pImpactorDiameter, pMass, pSprayEffects, pSprayScale), true) {
  }

  public Impact(Ocean pOcean, double pImpactorDiameter, double pMass, bool pSprayEffects) : this(TritonImpactPINVOKE.new_Impact__SWIG_1(Ocean.getCPtr(pOcean), pImpactorDiameter, pMass, pSprayEffects), true) {
  }

  public Impact(Ocean pOcean, double pImpactorDiameter, double pMass) : this(TritonImpactPINVOKE.new_Impact__SWIG_2(Ocean.getCPtr(pOcean), pImpactorDiameter, pMass), true) {
  }

  public void Trigger(Vector3 pPosition, Vector3 pDirection, double pVelocity, double pTime) {
    TritonImpactPINVOKE.Impact_Trigger(swigCPtr, Vector3.getCPtr(pPosition), Vector3.getCPtr(pDirection), pVelocity, pTime);
    if (TritonImpactPINVOKE.SWIGPendingException.Pending) throw TritonImpactPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetPosition() {
    Vector3 ret = new Vector3(TritonImpactPINVOKE.Impact_GetPosition(swigCPtr), true);
    return ret;
  }

  public double GetVelocity() {
    double ret = TritonImpactPINVOKE.Impact_GetVelocity(swigCPtr);
    return ret;
  }

}

}
