//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Matrix3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Matrix3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Matrix3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Matrix3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Matrix3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Matrix3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static Matrix3 Identity {
    set {
      TritonEnvironmentPINVOKE.Matrix3_Identity_set(Matrix3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Matrix3_Identity_get();
      Matrix3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Matrix3(cPtr, false);
      return ret;
    } 
  }

  public Matrix3() : this(TritonEnvironmentPINVOKE.new_Matrix3__SWIG_0(), true) {
  }

  public Matrix3(double e11, double e12, double e13, double e21, double e22, double e23, double e31, double e32, double e33) : this(TritonEnvironmentPINVOKE.new_Matrix3__SWIG_1(e11, e12, e13, e21, e22, e23, e31, e32, e33), true) {
  }

  public Matrix3(SWIGTYPE_p_double m) : this(TritonEnvironmentPINVOKE.new_Matrix3__SWIG_2(SWIGTYPE_p_double.getCPtr(m)), true) {
  }

  public void ToFloatArray(SWIGTYPE_p_float val) {
    TritonEnvironmentPINVOKE.Matrix3_ToFloatArray(swigCPtr, SWIGTYPE_p_float.getCPtr(val));
  }

  public void FromRx(double rad) {
    TritonEnvironmentPINVOKE.Matrix3_FromRx(swigCPtr, rad);
  }

  public void FromRy(double rad) {
    TritonEnvironmentPINVOKE.Matrix3_FromRy(swigCPtr, rad);
  }

  public void FromRz(double rad) {
    TritonEnvironmentPINVOKE.Matrix3_FromRz(swigCPtr, rad);
  }

  public void FromXYZ(double Rx, double Ry, double Rz) {
    TritonEnvironmentPINVOKE.Matrix3_FromXYZ(swigCPtr, Rx, Ry, Rz);
  }

  public Matrix3 Transpose() {
    Matrix3 ret = new Matrix3(TritonEnvironmentPINVOKE.Matrix3_Transpose(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_a_3__double elem {
    set {
      TritonEnvironmentPINVOKE.Matrix3_elem_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Matrix3_elem_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

}

}
