//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Matrix4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Matrix4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Matrix4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Matrix4 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Matrix4() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Matrix4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static Matrix4 Identity {
    set {
      TritonEnvironmentPINVOKE.Matrix4_Identity_set(Matrix4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Matrix4_Identity_get();
      Matrix4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Matrix4(cPtr, false);
      return ret;
    } 
  }

  public Matrix4() : this(TritonEnvironmentPINVOKE.new_Matrix4__SWIG_0(), true) {
  }

  public Matrix4(double e11, double e12, double e13, double e14, double e21, double e22, double e23, double e24, double e31, double e32, double e33, double e34, double e41, double e42, double e43, double e44) : this(TritonEnvironmentPINVOKE.new_Matrix4__SWIG_1(e11, e12, e13, e14, e21, e22, e23, e24, e31, e32, e33, e34, e41, e42, e43, e44), true) {
  }

  public Matrix4(SWIGTYPE_p_double m) : this(TritonEnvironmentPINVOKE.new_Matrix4__SWIG_2(SWIGTYPE_p_double.getCPtr(m)), true) {
  }

  public void ToFloatArray(SWIGTYPE_p_float val) {
    TritonEnvironmentPINVOKE.Matrix4_ToFloatArray(swigCPtr, SWIGTYPE_p_float.getCPtr(val));
  }

  public void Transpose() {
    TritonEnvironmentPINVOKE.Matrix4_Transpose(swigCPtr);
  }

  public Matrix4 InverseCramers(double epsilon) {
    Matrix4 ret = new Matrix4(TritonEnvironmentPINVOKE.Matrix4_InverseCramers__SWIG_0(swigCPtr, epsilon), true);
    return ret;
  }

  public Matrix4 InverseCramers() {
    Matrix4 ret = new Matrix4(TritonEnvironmentPINVOKE.Matrix4_InverseCramers__SWIG_1(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_double GetRow(int row) {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Matrix4_GetRow(swigCPtr, row);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_a_4__double elem {
    set {
      TritonEnvironmentPINVOKE.Matrix4_elem_set(swigCPtr, SWIGTYPE_p_a_4__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.Matrix4_elem_get(swigCPtr);
      SWIGTYPE_p_a_4__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_4__double(cPtr, false);
      return ret;
    } 
  }

}

}
