//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Ocean : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Ocean(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Ocean obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Ocean obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Ocean() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonOceanPINVOKE.delete_Ocean(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static Ocean Create(Environment env, WaterModelTypes type, bool enableHeightTests, bool enableBreakingWaves, OceanQuality quality) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_Create__SWIG_0(Environment.getCPtr(env), (int)type, enableHeightTests, enableBreakingWaves, (int)quality);
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

  public static Ocean Create(Environment env, WaterModelTypes type, bool enableHeightTests, bool enableBreakingWaves) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_Create__SWIG_1(Environment.getCPtr(env), (int)type, enableHeightTests, enableBreakingWaves);
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

  public static Ocean Create(Environment env, WaterModelTypes type, bool enableHeightTests) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_Create__SWIG_2(Environment.getCPtr(env), (int)type, enableHeightTests);
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

  public static Ocean Create(Environment env, WaterModelTypes type) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_Create__SWIG_3(Environment.getCPtr(env), (int)type);
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

  public static Ocean Create(Environment env) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_Create__SWIG_4(Environment.getCPtr(env));
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

  public virtual void Draw(double time, bool depthWrites, bool drawWater, bool drawParticles, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_0(swigCPtr, time, depthWrites, drawWater, drawParticles, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
  }

  public virtual void Draw(double time, bool depthWrites, bool drawWater, bool drawParticles, System.IntPtr context) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_1(swigCPtr, time, depthWrites, drawWater, drawParticles, context);
  }

  public virtual void Draw(double time, bool depthWrites, bool drawWater, bool drawParticles) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_2(swigCPtr, time, depthWrites, drawWater, drawParticles);
  }

  public virtual void Draw(double time, bool depthWrites, bool drawWater) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_3(swigCPtr, time, depthWrites, drawWater);
  }

  public virtual void Draw(double time, bool depthWrites) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_4(swigCPtr, time, depthWrites);
  }

  public virtual void Draw(double time) {
    TritonOceanPINVOKE.Ocean_Draw__SWIG_5(swigCPtr, time);
  }

  public virtual void DrawConcurrent(double time, bool depthWrites, bool drawWater, bool drawParticles, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_0(swigCPtr, time, depthWrites, drawWater, drawParticles, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
  }

  public virtual void DrawConcurrent(double time, bool depthWrites, bool drawWater, bool drawParticles, System.IntPtr context) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_1(swigCPtr, time, depthWrites, drawWater, drawParticles, context);
  }

  public virtual void DrawConcurrent(double time, bool depthWrites, bool drawWater, bool drawParticles) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_2(swigCPtr, time, depthWrites, drawWater, drawParticles);
  }

  public virtual void DrawConcurrent(double time, bool depthWrites, bool drawWater) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_3(swigCPtr, time, depthWrites, drawWater);
  }

  public virtual void DrawConcurrent(double time, bool depthWrites) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_4(swigCPtr, time, depthWrites);
  }

  public virtual void DrawConcurrent(double time) {
    TritonOceanPINVOKE.Ocean_DrawConcurrent__SWIG_5(swigCPtr, time);
  }

  public void PostDrawConcurrent() {
    TritonOceanPINVOKE.Ocean_PostDrawConcurrent(swigCPtr);
  }

  public virtual bool SetPatchShader(double time, int vertexStride, int positionOffset, bool doublePrecisionVertices, SWIGTYPE_p_double modelMatrix, bool decalPass, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchShader__SWIG_0(swigCPtr, time, vertexStride, positionOffset, doublePrecisionVertices, SWIGTYPE_p_double.getCPtr(modelMatrix), decalPass, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    return ret;
  }

  public virtual bool SetPatchShader(double time, int vertexStride, int positionOffset, bool doublePrecisionVertices, SWIGTYPE_p_double modelMatrix, bool decalPass, System.IntPtr context) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchShader__SWIG_1(swigCPtr, time, vertexStride, positionOffset, doublePrecisionVertices, SWIGTYPE_p_double.getCPtr(modelMatrix), decalPass, context);
    return ret;
  }

  public virtual bool SetPatchShader(double time, int vertexStride, int positionOffset, bool doublePrecisionVertices, SWIGTYPE_p_double modelMatrix, bool decalPass) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchShader__SWIG_2(swigCPtr, time, vertexStride, positionOffset, doublePrecisionVertices, SWIGTYPE_p_double.getCPtr(modelMatrix), decalPass);
    return ret;
  }

  public virtual bool SetPatchShader(double time, int vertexStride, int positionOffset, bool doublePrecisionVertices, SWIGTYPE_p_double modelMatrix) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchShader__SWIG_3(swigCPtr, time, vertexStride, positionOffset, doublePrecisionVertices, SWIGTYPE_p_double.getCPtr(modelMatrix));
    return ret;
  }

  public virtual bool SetPatchShader(double time, int vertexStride, int positionOffset, bool doublePrecisionVertices) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchShader__SWIG_4(swigCPtr, time, vertexStride, positionOffset, doublePrecisionVertices);
    return ret;
  }

  public virtual bool SetPatchMatrix(SWIGTYPE_p_double modelMatrix, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchMatrix__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(modelMatrix), context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    return ret;
  }

  public virtual bool SetPatchMatrix(SWIGTYPE_p_double modelMatrix, System.IntPtr context) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchMatrix__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(modelMatrix), context);
    return ret;
  }

  public virtual bool SetPatchMatrix(SWIGTYPE_p_double modelMatrix) {
    bool ret = TritonOceanPINVOKE.Ocean_SetPatchMatrix__SWIG_2(swigCPtr, SWIGTYPE_p_double.getCPtr(modelMatrix));
    return ret;
  }

  public virtual void UnsetPatchShader(double time, TBoundingBox patchBounds, bool decalPass, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_0(swigCPtr, time, TBoundingBox.getCPtr(patchBounds), decalPass, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
  }

  public virtual void UnsetPatchShader(double time, TBoundingBox patchBounds, bool decalPass, System.IntPtr context) {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_1(swigCPtr, time, TBoundingBox.getCPtr(patchBounds), decalPass, context);
  }

  public virtual void UnsetPatchShader(double time, TBoundingBox patchBounds, bool decalPass) {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_2(swigCPtr, time, TBoundingBox.getCPtr(patchBounds), decalPass);
  }

  public virtual void UnsetPatchShader(double time, TBoundingBox patchBounds) {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_3(swigCPtr, time, TBoundingBox.getCPtr(patchBounds));
  }

  public virtual void UnsetPatchShader(double time) {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_4(swigCPtr, time);
  }

  public virtual void UnsetPatchShader() {
    TritonOceanPINVOKE.Ocean_UnsetPatchShader__SWIG_5(swigCPtr);
  }

  public virtual bool Initialize(System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_Initialize(swigCPtr, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    return ret;
  }

  public virtual void UpdateSimulation(double time, SWIGTYPE_p_Triton__Camera camera) {
    TritonOceanPINVOKE.Ocean_UpdateSimulation__SWIG_0(swigCPtr, time, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
  }

  public virtual void UpdateSimulation(double time) {
    TritonOceanPINVOKE.Ocean_UpdateSimulation__SWIG_1(swigCPtr, time);
  }

  public void D3D9DeviceLost() {
    TritonOceanPINVOKE.Ocean_D3D9DeviceLost(swigCPtr);
  }

  public void D3D9DeviceReset() {
    TritonOceanPINVOKE.Ocean_D3D9DeviceReset(swigCPtr);
  }

  public float GetChoppiness() {
    float ret = TritonOceanPINVOKE.Ocean_GetChoppiness(swigCPtr);
    return ret;
  }

  public void SetChoppiness(float chop) {
    TritonOceanPINVOKE.Ocean_SetChoppiness(swigCPtr, chop);
  }

  public float GetLoopingPeriod() {
    float ret = TritonOceanPINVOKE.Ocean_GetLoopingPeriod(swigCPtr);
    return ret;
  }

  public void SetLoopingPeriod(float loopingPeriod) {
    TritonOceanPINVOKE.Ocean_SetLoopingPeriod(swigCPtr, loopingPeriod);
  }

  public float GetDepth(Vector3 floorNormal, SWIGTYPE_p_Triton__Camera camera) {
    float ret = TritonOceanPINVOKE.Ocean_GetDepth__SWIG_0(swigCPtr, Vector3.getCPtr(floorNormal), SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetDepth(Vector3 floorNormal) {
    float ret = TritonOceanPINVOKE.Ocean_GetDepth__SWIG_1(swigCPtr, Vector3.getCPtr(floorNormal));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDepth(float depth, Vector3 floorNormal, SWIGTYPE_p_Triton__Camera camera) {
    TritonOceanPINVOKE.Ocean_SetDepth__SWIG_0(swigCPtr, depth, Vector3.getCPtr(floorNormal), SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetDepth(float depth, Vector3 floorNormal) {
    TritonOceanPINVOKE.Ocean_SetDepth__SWIG_1(swigCPtr, depth, Vector3.getCPtr(floorNormal));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void EnableWireframe(bool wireframeOn) {
    TritonOceanPINVOKE.Ocean_EnableWireframe(swigCPtr, wireframeOn);
  }

  public string GetFFTName() {
    string ret = TritonOceanPINVOKE.Ocean_GetFFTName(swigCPtr);
    return ret;
  }

  public uint GetNumTriangles() {
    uint ret = TritonOceanPINVOKE.Ocean_GetNumTriangles(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_ShaderHandle GetShaderObject(Shaders shaderProgram, System.IntPtr context, SWIGTYPE_p_Triton__Camera camera) {
    SWIGTYPE_p_ShaderHandle ret = new SWIGTYPE_p_ShaderHandle(TritonOceanPINVOKE.Ocean_GetShaderObject__SWIG_0(swigCPtr, (int)shaderProgram, context, SWIGTYPE_p_Triton__Camera.getCPtr(camera)), true);
    return ret;
  }

  public SWIGTYPE_p_ShaderHandle GetShaderObject(Shaders shaderProgram, System.IntPtr context) {
    SWIGTYPE_p_ShaderHandle ret = new SWIGTYPE_p_ShaderHandle(TritonOceanPINVOKE.Ocean_GetShaderObject__SWIG_1(swigCPtr, (int)shaderProgram, context), true);
    return ret;
  }

  public SWIGTYPE_p_ShaderHandle GetShaderObject(Shaders shaderProgram) {
    SWIGTYPE_p_ShaderHandle ret = new SWIGTYPE_p_ShaderHandle(TritonOceanPINVOKE.Ocean_GetShaderObject__SWIG_2(swigCPtr, (int)shaderProgram), true);
    return ret;
  }

  public SWIGTYPE_p_Triton__WakeManager GetWakeManager() {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_GetWakeManager(swigCPtr);
    SWIGTYPE_p_Triton__WakeManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__WakeManager(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_Triton__DecalManager GetDecalManager() {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_GetDecalManager(swigCPtr);
    SWIGTYPE_p_Triton__DecalManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Triton__DecalManager(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_DecalHandle AddDecal(System.IntPtr texture, float size, Vector3 position) {
    SWIGTYPE_p_DecalHandle ret = new SWIGTYPE_p_DecalHandle(TritonOceanPINVOKE.Ocean_AddDecal(swigCPtr, texture, size, Vector3.getCPtr(position)), true);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ScaleDecal(SWIGTYPE_p_DecalHandle decal, float scaleWidth, float scaleDepth) {
    TritonOceanPINVOKE.Ocean_ScaleDecal(swigCPtr, SWIGTYPE_p_DecalHandle.getCPtr(decal), scaleWidth, scaleDepth);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void MoveDecal(SWIGTYPE_p_DecalHandle decal, Vector3 position) {
    TritonOceanPINVOKE.Ocean_MoveDecal(swigCPtr, SWIGTYPE_p_DecalHandle.getCPtr(decal), Vector3.getCPtr(position));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RotateDecal(SWIGTYPE_p_DecalHandle decal, double radians) {
    TritonOceanPINVOKE.Ocean_RotateDecal(swigCPtr, SWIGTYPE_p_DecalHandle.getCPtr(decal), radians);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetDecalAlpha(SWIGTYPE_p_DecalHandle decal, float alpha) {
    TritonOceanPINVOKE.Ocean_SetDecalAlpha(swigCPtr, SWIGTYPE_p_DecalHandle.getCPtr(decal), alpha);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveDecal(SWIGTYPE_p_DecalHandle decal) {
    TritonOceanPINVOKE.Ocean_RemoveDecal(swigCPtr, SWIGTYPE_p_DecalHandle.getCPtr(decal));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes, bool highResolution, bool threadSafe, Vector3 intersectionPoint, bool autoFlip, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_0(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes, highResolution, threadSafe, Vector3.getCPtr(intersectionPoint), autoFlip, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes, bool highResolution, bool threadSafe, Vector3 intersectionPoint, bool autoFlip) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_1(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes, highResolution, threadSafe, Vector3.getCPtr(intersectionPoint), autoFlip);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes, bool highResolution, bool threadSafe, Vector3 intersectionPoint) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_2(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes, highResolution, threadSafe, Vector3.getCPtr(intersectionPoint));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes, bool highResolution, bool threadSafe) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_3(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes, highResolution, threadSafe);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes, bool highResolution) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_4(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes, highResolution);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation, bool includeWakes) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_5(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation, includeWakes);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal, bool visualCorrelation) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_6(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal), visualCorrelation);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetHeight(Vector3 point, Vector3 direction, SWIGTYPE_p_float height, Vector3 normal) {
    bool ret = TritonOceanPINVOKE.Ocean_GetHeight__SWIG_7(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), SWIGTYPE_p_float.getCPtr(height), Vector3.getCPtr(normal));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetWavesIntersection(Vector3 point, Vector3 direction, Vector3 normal, Vector3 intersectionPoint, double precision, bool visualCorrelation, bool threadSafe, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_GetWavesIntersection__SWIG_0(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(normal), Vector3.getCPtr(intersectionPoint), precision, visualCorrelation, threadSafe, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetWavesIntersection(Vector3 point, Vector3 direction, Vector3 normal, Vector3 intersectionPoint, double precision, bool visualCorrelation, bool threadSafe) {
    bool ret = TritonOceanPINVOKE.Ocean_GetWavesIntersection__SWIG_1(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(normal), Vector3.getCPtr(intersectionPoint), precision, visualCorrelation, threadSafe);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetWavesIntersection(Vector3 point, Vector3 direction, Vector3 normal, Vector3 intersectionPoint, double precision, bool visualCorrelation) {
    bool ret = TritonOceanPINVOKE.Ocean_GetWavesIntersection__SWIG_2(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(normal), Vector3.getCPtr(intersectionPoint), precision, visualCorrelation);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetWavesIntersection(Vector3 point, Vector3 direction, Vector3 normal, Vector3 intersectionPoint, double precision) {
    bool ret = TritonOceanPINVOKE.Ocean_GetWavesIntersection__SWIG_3(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(normal), Vector3.getCPtr(intersectionPoint), precision);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetWavesIntersection(Vector3 point, Vector3 direction, Vector3 normal, Vector3 intersectionPoint) {
    bool ret = TritonOceanPINVOKE.Ocean_GetWavesIntersection__SWIG_4(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(normal), Vector3.getCPtr(intersectionPoint));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetIntersection(Vector3 point, Vector3 direction, Vector3 intersection, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_GetIntersection__SWIG_0(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(intersection), SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetIntersection(Vector3 point, Vector3 direction, Vector3 intersection) {
    bool ret = TritonOceanPINVOKE.Ocean_GetIntersection__SWIG_1(swigCPtr, Vector3.getCPtr(point), Vector3.getCPtr(direction), Vector3.getCPtr(intersection));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetWaveHeading() {
    float ret = TritonOceanPINVOKE.Ocean_GetWaveHeading(swigCPtr);
    return ret;
  }

  public void EnableSpray(bool enable) {
    TritonOceanPINVOKE.Ocean_EnableSpray(swigCPtr, enable);
  }

  public bool SprayEnabled() {
    bool ret = TritonOceanPINVOKE.Ocean_SprayEnabled(swigCPtr);
    return ret;
  }

  public void SetRefractionColor(Vector3 refractionColor) {
    TritonOceanPINVOKE.Ocean_SetRefractionColor(swigCPtr, Vector3.getCPtr(refractionColor));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetRefractionColor() {
    Vector3 ret = new Vector3(TritonOceanPINVOKE.Ocean_GetRefractionColor(swigCPtr), false);
    return ret;
  }

  public void SetReflectionScale(float reflectionScale) {
    TritonOceanPINVOKE.Ocean_SetReflectionScale(swigCPtr, reflectionScale);
  }

  public float GetReflectionScale() {
    float ret = TritonOceanPINVOKE.Ocean_GetReflectionScale(swigCPtr);
    return ret;
  }

  public void SetPlanarReflectionBlend(float blendPercent) {
    TritonOceanPINVOKE.Ocean_SetPlanarReflectionBlend(swigCPtr, blendPercent);
  }

  public float GetPlanarReflectionBlend() {
    float ret = TritonOceanPINVOKE.Ocean_GetPlanarReflectionBlend(swigCPtr);
    return ret;
  }

  public bool ComputeReflectionMatrices(Matrix4 reflectionMatrix, Matrix3 textureMatrix, SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_ComputeReflectionMatrices__SWIG_0(swigCPtr, Matrix4.getCPtr(reflectionMatrix), Matrix3.getCPtr(textureMatrix), SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ComputeReflectionMatrices(Matrix4 reflectionMatrix, Matrix3 textureMatrix) {
    bool ret = TritonOceanPINVOKE.Ocean_ComputeReflectionMatrices__SWIG_1(swigCPtr, Matrix4.getCPtr(reflectionMatrix), Matrix3.getCPtr(textureMatrix));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Environment GetEnvironment() {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_GetEnvironment(swigCPtr);
    Environment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Environment(cPtr, false);
    return ret;
  }

  public virtual bool IsCameraAboveWater(SWIGTYPE_p_Triton__Camera camera) {
    bool ret = TritonOceanPINVOKE.Ocean_IsCameraAboveWater__SWIG_0(swigCPtr, SWIGTYPE_p_Triton__Camera.getCPtr(camera));
    return ret;
  }

  public virtual bool IsCameraAboveWater() {
    bool ret = TritonOceanPINVOKE.Ocean_IsCameraAboveWater__SWIG_1(swigCPtr);
    return ret;
  }

  public void SetDepthOffset(float offset) {
    TritonOceanPINVOKE.Ocean_SetDepthOffset(swigCPtr, offset);
  }

  public float GetDepthOffset() {
    float ret = TritonOceanPINVOKE.Ocean_GetDepthOffset(swigCPtr);
    return ret;
  }

  public void SetDisplacementDampingDistance(double distance) {
    TritonOceanPINVOKE.Ocean_SetDisplacementDampingDistance(swigCPtr, distance);
  }

  public double GetDisplacementDampingDistance() {
    double ret = TritonOceanPINVOKE.Ocean_GetDisplacementDampingDistance(swigCPtr);
    return ret;
  }

  public void EnableGodRays(bool enable) {
    TritonOceanPINVOKE.Ocean_EnableGodRays(swigCPtr, enable);
  }

  public bool GodRaysEnabled() {
    bool ret = TritonOceanPINVOKE.Ocean_GodRaysEnabled(swigCPtr);
    return ret;
  }

  public void SetGodRaysFade(float fadeAmount) {
    TritonOceanPINVOKE.Ocean_SetGodRaysFade(swigCPtr, fadeAmount);
  }

  public float GetGodRaysFade() {
    float ret = TritonOceanPINVOKE.Ocean_GetGodRaysFade(swigCPtr);
    return ret;
  }

  public void Lock() {
    TritonOceanPINVOKE.Ocean_Lock(swigCPtr);
  }

  public void Unlock() {
    TritonOceanPINVOKE.Ocean_Unlock(swigCPtr);
  }

  public void SetQuality(OceanQuality quality) {
    TritonOceanPINVOKE.Ocean_SetQuality(swigCPtr, (int)quality);
  }

  public OceanQuality GetQuality() {
    OceanQuality ret = (OceanQuality)TritonOceanPINVOKE.Ocean_GetQuality(swigCPtr);
    return ret;
  }

  public void SetLinearColorSpace(bool linearOn) {
    TritonOceanPINVOKE.Ocean_SetLinearColorSpace(swigCPtr, linearOn);
  }

  public bool GetLinearColorSpace() {
    bool ret = TritonOceanPINVOKE.Ocean_GetLinearColorSpace(swigCPtr);
    return ret;
  }

  public void SetMaximumWavePeriod(double maxPeriod) {
    TritonOceanPINVOKE.Ocean_SetMaximumWavePeriod(swigCPtr, maxPeriod);
  }

  public double GetMaximumWavePeriod() {
    double ret = TritonOceanPINVOKE.Ocean_GetMaximumWavePeriod(swigCPtr);
    return ret;
  }

  public void SetClipDistances(double nearClip, double farClip) {
    TritonOceanPINVOKE.Ocean_SetClipDistances(swigCPtr, nearClip, farClip);
  }

  public void GetClipDistances(SWIGTYPE_p_double nearClip, SWIGTYPE_p_double farClip) {
    TritonOceanPINVOKE.Ocean_GetClipDistances(swigCPtr, SWIGTYPE_p_double.getCPtr(nearClip), SWIGTYPE_p_double.getCPtr(farClip));
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool OverrideFFTInputArray(TritComplex H0, uint size) {
    bool ret = TritonOceanPINVOKE.Ocean_OverrideFFTInputArray(swigCPtr, TritComplex.getCPtr(H0), size);
    return ret;
  }

  public void ClearFFTInputArray() {
    TritonOceanPINVOKE.Ocean_ClearFFTInputArray(swigCPtr);
  }

  public TritComplex GetFFTInputArray(SWIGTYPE_p_unsigned_int size) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.Ocean_GetFFTInputArray(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(size));
    TritComplex ret = (cPtr == global::System.IntPtr.Zero) ? null : new TritComplex(cPtr, false);
    if (TritonOceanPINVOKE.SWIGPendingException.Pending) throw TritonOceanPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetRotorWashUseDecals(bool useDecals) {
    TritonOceanPINVOKE.Ocean_SetRotorWashUseDecals(swigCPtr, useDecals);
  }

  public bool GetRotorWashUseDecals() {
    bool ret = TritonOceanPINVOKE.Ocean_GetRotorWashUseDecals(swigCPtr);
    return ret;
  }

  public void SetWaterModel(WaterModelTypes waterModel) {
    TritonOceanPINVOKE.Ocean_SetWaterModel(swigCPtr, (int)waterModel);
  }

  public WaterModelTypes GetWaterModel() {
    WaterModelTypes ret = (WaterModelTypes)TritonOceanPINVOKE.Ocean_GetWaterModel(swigCPtr);
    return ret;
  }

  public Ocean() : this(TritonOceanPINVOKE.new_Ocean(), true) {
  }

}

}
