//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public enum Renderer {
  OPENGL_2_0,
  OPENGL_3_2,
  OPENGL_4_0,
  OPENGL_4_1,
  OPENGL_4_5,
  DIRECTX_9,
  DIRECT3D9_EX,
  DIRECTX_11,
  NO_RENDERER
}

}
