//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class ResourceLoader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ResourceLoader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ResourceLoader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(ResourceLoader obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ResourceLoader() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_ResourceLoader(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ResourceLoader(string resourceDirPath, bool useAddDllDirectory) : this(TritonEnvironmentPINVOKE.new_ResourceLoader__SWIG_0(resourceDirPath, useAddDllDirectory), true) {
  }

  public ResourceLoader(string resourceDirPath) : this(TritonEnvironmentPINVOKE.new_ResourceLoader__SWIG_1(resourceDirPath), true) {
  }

  public virtual void SetResourceDirPath(string path, bool useAddDllDirectory) {
    TritonEnvironmentPINVOKE.ResourceLoader_SetResourceDirPath__SWIG_0(swigCPtr, path, useAddDllDirectory);
  }

  public virtual void SetResourceDirPath(string path) {
    TritonEnvironmentPINVOKE.ResourceLoader_SetResourceDirPath__SWIG_1(swigCPtr, path);
  }

  public virtual string GetResourceDirPath() {
    string ret = TritonEnvironmentPINVOKE.ResourceLoader_GetResourceDirPath(swigCPtr);
    return ret;
  }

  public virtual bool LoadResource(string pathName, string data, SWIGTYPE_p_unsigned_int dataLen, bool text) {
    bool ret = TritonEnvironmentPINVOKE.ResourceLoader_LoadResource(swigCPtr, pathName, data, SWIGTYPE_p_unsigned_int.getCPtr(dataLen), text);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void FreeResource(string data) {
    TritonEnvironmentPINVOKE.ResourceLoader_FreeResource(swigCPtr, data);
  }

}

}
