//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class RotorWash : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public RotorWash(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(RotorWash obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(RotorWash obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RotorWash() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonRotorWashPINVOKE.delete_RotorWash(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public RotorWash(Ocean pOcean, double pRotorDiameter, bool pSprayEffects, bool pUseDecals) : this(TritonRotorWashPINVOKE.new_RotorWash__SWIG_0(Ocean.getCPtr(pOcean), pRotorDiameter, pSprayEffects, pUseDecals), true) {
  }

  public RotorWash(Ocean pOcean, double pRotorDiameter, bool pSprayEffects) : this(TritonRotorWashPINVOKE.new_RotorWash__SWIG_1(Ocean.getCPtr(pOcean), pRotorDiameter, pSprayEffects), true) {
  }

  public RotorWash(Ocean pOcean, double pRotorDiameter) : this(TritonRotorWashPINVOKE.new_RotorWash__SWIG_2(Ocean.getCPtr(pOcean), pRotorDiameter), true) {
  }

  public void Update(Vector3 pPosition, Vector3 pDirection, double pVelocity, double pTime) {
    TritonRotorWashPINVOKE.RotorWash_Update(swigCPtr, Vector3.getCPtr(pPosition), Vector3.getCPtr(pDirection), pVelocity, pTime);
    if (TritonRotorWashPINVOKE.SWIGPendingException.Pending) throw TritonRotorWashPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3 GetPosition() {
    Vector3 ret = new Vector3(TritonRotorWashPINVOKE.RotorWash_GetPosition(swigCPtr), true);
    return ret;
  }

  public double GetVelocity() {
    double ret = TritonRotorWashPINVOKE.RotorWash_GetVelocity(swigCPtr);
    return ret;
  }

  public void OceanDestroyed() {
    TritonRotorWashPINVOKE.RotorWash_OceanDestroyed(swigCPtr);
  }

  public void OceanQualityChanged() {
    TritonRotorWashPINVOKE.RotorWash_OceanQualityChanged(swigCPtr);
  }

  public void setUseDecals(bool useDecals) {
    TritonRotorWashPINVOKE.RotorWash_setUseDecals(swigCPtr, useDecals);
  }

  public bool GetUseDecals() {
    bool ret = TritonRotorWashPINVOKE.RotorWash_GetUseDecals(swigCPtr);
    return ret;
  }

}

}
