//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class SBowSprayEmitter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public SBowSprayEmitter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SBowSprayEmitter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(SBowSprayEmitter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SBowSprayEmitter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonWakeGeneratorPINVOKE.delete_SBowSprayEmitter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int numSprays {
    set {
      TritonWakeGeneratorPINVOKE.SBowSprayEmitter_numSprays_set(swigCPtr, value);
    } 
    get {
      int ret = TritonWakeGeneratorPINVOKE.SBowSprayEmitter_numSprays_get(swigCPtr);
      return ret;
    } 
  }

  public Vector3f offset {
    set {
      TritonWakeGeneratorPINVOKE.SBowSprayEmitter_offset_set(swigCPtr, Vector3f.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonWakeGeneratorPINVOKE.SBowSprayEmitter_offset_get(swigCPtr);
      Vector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3f(cPtr, false);
      return ret;
    } 
  }

  public double sprayVelocityScale {
    set {
      TritonWakeGeneratorPINVOKE.SBowSprayEmitter_sprayVelocityScale_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.SBowSprayEmitter_sprayVelocityScale_get(swigCPtr);
      return ret;
    } 
  }

  public double spraySizeScale {
    set {
      TritonWakeGeneratorPINVOKE.SBowSprayEmitter_spraySizeScale_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.SBowSprayEmitter_spraySizeScale_get(swigCPtr);
      return ret;
    } 
  }

  public SBowSprayEmitter(int _numSprays, double _sprayVelocityScale, double _spraySizeScale) : this(TritonWakeGeneratorPINVOKE.new_SBowSprayEmitter(_numSprays, _sprayVelocityScale, _spraySizeScale), true) {
  }

}

}
