//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public enum Shaders {
  WATER_SURFACE,
  WATER_SURFACE_PATCH,
  SPRAY_PARTICLES,
  WAKE_SPRAY_PARTICLES,
  GOD_RAYS,
  WATER_DECALS
}

}
