//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class SwellDescription : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public SwellDescription(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SwellDescription obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(SwellDescription obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SwellDescription() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_SwellDescription(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float wavelength {
    set {
      TritonEnvironmentPINVOKE.SwellDescription_wavelength_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.SwellDescription_wavelength_get(swigCPtr);
      return ret;
    } 
  }

  public float height {
    set {
      TritonEnvironmentPINVOKE.SwellDescription_height_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.SwellDescription_height_get(swigCPtr);
      return ret;
    } 
  }

  public float direction {
    set {
      TritonEnvironmentPINVOKE.SwellDescription_direction_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.SwellDescription_direction_get(swigCPtr);
      return ret;
    } 
  }

  public float phase {
    set {
      TritonEnvironmentPINVOKE.SwellDescription_phase_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.SwellDescription_phase_get(swigCPtr);
      return ret;
    } 
  }

  public SwellDescription() : this(TritonEnvironmentPINVOKE.new_SwellDescription(), true) {
  }

}

}
