//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class SWIGTYPE_p_Triton__OrientedBoundingBox {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public SWIGTYPE_p_Triton__OrientedBoundingBox(global::System.IntPtr cPtr, bool futureUse) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public SWIGTYPE_p_Triton__OrientedBoundingBox() {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SWIGTYPE_p_Triton__OrientedBoundingBox obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(SWIGTYPE_p_Triton__OrientedBoundingBox obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }
}

}
