//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class TBoundingBox : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public TBoundingBox(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(TBoundingBox obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(TBoundingBox obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TBoundingBox() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_TBoundingBox(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TBoundingBox() : this(TritonEnvironmentPINVOKE.new_TBoundingBox__SWIG_0(), true) {
  }

  public TBoundingBox(Vector3 vMin, Vector3 vMax) : this(TritonEnvironmentPINVOKE.new_TBoundingBox__SWIG_1(Vector3.getCPtr(vMin), Vector3.getCPtr(vMax)), true) {
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public TBoundingBox(double minX, double minY, double minZ, double maxX, double maxY, double maxZ) : this(TritonEnvironmentPINVOKE.new_TBoundingBox__SWIG_2(minX, minY, minZ, maxX, maxY, maxZ), true) {
  }

  public bool Contains(Vector3 v) {
    bool ret = TritonEnvironmentPINVOKE.TBoundingBox_Contains(swigCPtr, Vector3.getCPtr(v));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3 m_vMin {
    set {
      TritonEnvironmentPINVOKE.TBoundingBox_m_vMin_set(swigCPtr, Vector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.TBoundingBox_m_vMin_get(swigCPtr);
      Vector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3(cPtr, false);
      return ret;
    } 
  }

  public Vector3 m_vMax {
    set {
      TritonEnvironmentPINVOKE.TBoundingBox_m_vMax_set(swigCPtr, Vector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.TBoundingBox_m_vMax_get(swigCPtr);
      Vector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3(cPtr, false);
      return ret;
    } 
  }

}

}
