//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class TidalStreamWake : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public TidalStreamWake(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(TidalStreamWake obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(TidalStreamWake obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TidalStreamWake() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonTidalStreamWakePINVOKE.delete_TidalStreamWake(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TidalStreamWake(Ocean pOcean, double pSize, double pDraft, double pWaveMax, double pOffset, bool pUseDecals, bool pUseDisplacement) : this(TritonTidalStreamWakePINVOKE.new_TidalStreamWake__SWIG_0(Ocean.getCPtr(pOcean), pSize, pDraft, pWaveMax, pOffset, pUseDecals, pUseDisplacement), true) {
  }

  public TidalStreamWake(Ocean pOcean, double pSize, double pDraft, double pWaveMax, double pOffset, bool pUseDecals) : this(TritonTidalStreamWakePINVOKE.new_TidalStreamWake__SWIG_1(Ocean.getCPtr(pOcean), pSize, pDraft, pWaveMax, pOffset, pUseDecals), true) {
  }

  public TidalStreamWake(Ocean pOcean, double pSize, double pDraft, double pWaveMax, double pOffset) : this(TritonTidalStreamWakePINVOKE.new_TidalStreamWake__SWIG_2(Ocean.getCPtr(pOcean), pSize, pDraft, pWaveMax, pOffset), true) {
  }

  public TidalStreamWake(Ocean pOcean, double pSize, double pDraft, double pWaveMax) : this(TritonTidalStreamWakePINVOKE.new_TidalStreamWake__SWIG_3(Ocean.getCPtr(pOcean), pSize, pDraft, pWaveMax), true) {
  }

  public TidalStreamWake(Ocean pOcean, double pSize, double pDraft) : this(TritonTidalStreamWakePINVOKE.new_TidalStreamWake__SWIG_4(Ocean.getCPtr(pOcean), pSize, pDraft), true) {
  }

  public void Update(Vector3 pPosition, Vector3 pDirection, double pVelocity, double pTime) {
    TritonTidalStreamWakePINVOKE.TidalStreamWake_Update(swigCPtr, Vector3.getCPtr(pPosition), Vector3.getCPtr(pDirection), pVelocity, pTime);
    if (TritonTidalStreamWakePINVOKE.SWIGPendingException.Pending) throw TritonTidalStreamWakePINVOKE.SWIGPendingException.Retrieve();
  }

  public void OceanDestroyed() {
    TritonTidalStreamWakePINVOKE.TidalStreamWake_OceanDestroyed(swigCPtr);
  }

  public void WakeManagerDestroyed() {
    TritonTidalStreamWakePINVOKE.TidalStreamWake_WakeManagerDestroyed(swigCPtr);
  }

  public void OceanQualityChanged() {
    TritonTidalStreamWakePINVOKE.TidalStreamWake_OceanQualityChanged(swigCPtr);
  }

}

}
