//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

class TritonOceanPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionCallbacks_TritonOcean")]
    public static extern void SWIGRegisterExceptionCallbacks_TritonOcean(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_TritonOcean")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_TritonOcean(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_TritonOcean(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_TritonOcean(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterStringCallback_TritonOcean")]
    public static extern void SWIGRegisterStringCallback_TritonOcean(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_TritonOcean(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static TritonOceanPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_floatp")]
  public static extern global::System.IntPtr new_floatp();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_copy_floatp")]
  public static extern global::System.IntPtr copy_floatp(float jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_floatp")]
  public static extern void delete_floatp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_floatp_assign")]
  public static extern void floatp_assign(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_floatp_value")]
  public static extern float floatp_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TritComplex_real_set")]
  public static extern void TritComplex_real_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TritComplex_real_get")]
  public static extern float TritComplex_real_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TritComplex_imaginary_set")]
  public static extern void TritComplex_imaginary_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TritComplex_imaginary_get")]
  public static extern float TritComplex_imaginary_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_TritComplex")]
  public static extern global::System.IntPtr new_TritComplex();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_TritComplex")]
  public static extern void delete_TritComplex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Create__SWIG_0")]
  public static extern global::System.IntPtr Ocean_Create__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3, bool jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Create__SWIG_1")]
  public static extern global::System.IntPtr Ocean_Create__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Create__SWIG_2")]
  public static extern global::System.IntPtr Ocean_Create__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Create__SWIG_3")]
  public static extern global::System.IntPtr Ocean_Create__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Create__SWIG_4")]
  public static extern global::System.IntPtr Ocean_Create__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Ocean")]
  public static extern void delete_Ocean(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_0")]
  public static extern void Ocean_Draw__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5, System.IntPtr jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_1")]
  public static extern void Ocean_Draw__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5, System.IntPtr jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_2")]
  public static extern void Ocean_Draw__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_3")]
  public static extern void Ocean_Draw__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_4")]
  public static extern void Ocean_Draw__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Draw__SWIG_5")]
  public static extern void Ocean_Draw__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_0")]
  public static extern void Ocean_DrawConcurrent__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5, System.IntPtr jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_1")]
  public static extern void Ocean_DrawConcurrent__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5, System.IntPtr jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_2")]
  public static extern void Ocean_DrawConcurrent__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_3")]
  public static extern void Ocean_DrawConcurrent__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_4")]
  public static extern void Ocean_DrawConcurrent__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_DrawConcurrent__SWIG_5")]
  public static extern void Ocean_DrawConcurrent__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_PostDrawConcurrent")]
  public static extern void Ocean_PostDrawConcurrent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchShader__SWIG_0")]
  public static extern bool Ocean_SetPatchShader__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3, int jarg4, bool jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, bool jarg7, System.IntPtr jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchShader__SWIG_1")]
  public static extern bool Ocean_SetPatchShader__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3, int jarg4, bool jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, bool jarg7, System.IntPtr jarg8);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchShader__SWIG_2")]
  public static extern bool Ocean_SetPatchShader__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3, int jarg4, bool jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchShader__SWIG_3")]
  public static extern bool Ocean_SetPatchShader__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3, int jarg4, bool jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchShader__SWIG_4")]
  public static extern bool Ocean_SetPatchShader__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3, int jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchMatrix__SWIG_0")]
  public static extern bool Ocean_SetPatchMatrix__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, System.IntPtr jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchMatrix__SWIG_1")]
  public static extern bool Ocean_SetPatchMatrix__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPatchMatrix__SWIG_2")]
  public static extern bool Ocean_SetPatchMatrix__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_0")]
  public static extern void Ocean_UnsetPatchShader__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, bool jarg4, System.IntPtr jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_1")]
  public static extern void Ocean_UnsetPatchShader__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, bool jarg4, System.IntPtr jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_2")]
  public static extern void Ocean_UnsetPatchShader__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_3")]
  public static extern void Ocean_UnsetPatchShader__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_4")]
  public static extern void Ocean_UnsetPatchShader__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UnsetPatchShader__SWIG_5")]
  public static extern void Ocean_UnsetPatchShader__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Initialize")]
  public static extern bool Ocean_Initialize(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UpdateSimulation__SWIG_0")]
  public static extern void Ocean_UpdateSimulation__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_UpdateSimulation__SWIG_1")]
  public static extern void Ocean_UpdateSimulation__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_D3D9DeviceLost")]
  public static extern void Ocean_D3D9DeviceLost(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_D3D9DeviceReset")]
  public static extern void Ocean_D3D9DeviceReset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetChoppiness")]
  public static extern float Ocean_GetChoppiness(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetChoppiness")]
  public static extern void Ocean_SetChoppiness(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetLoopingPeriod")]
  public static extern float Ocean_GetLoopingPeriod(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetLoopingPeriod")]
  public static extern void Ocean_SetLoopingPeriod(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetDepth__SWIG_0")]
  public static extern float Ocean_GetDepth__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetDepth__SWIG_1")]
  public static extern float Ocean_GetDepth__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetDepth__SWIG_0")]
  public static extern void Ocean_SetDepth__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetDepth__SWIG_1")]
  public static extern void Ocean_SetDepth__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_EnableWireframe")]
  public static extern void Ocean_EnableWireframe(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetFFTName")]
  public static extern string Ocean_GetFFTName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetNumTriangles")]
  public static extern uint Ocean_GetNumTriangles(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetShaderObject__SWIG_0")]
  public static extern global::System.IntPtr Ocean_GetShaderObject__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, System.IntPtr jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetShaderObject__SWIG_1")]
  public static extern global::System.IntPtr Ocean_GetShaderObject__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetShaderObject__SWIG_2")]
  public static extern global::System.IntPtr Ocean_GetShaderObject__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWakeManager")]
  public static extern global::System.IntPtr Ocean_GetWakeManager(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetDecalManager")]
  public static extern global::System.IntPtr Ocean_GetDecalManager(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_AddDecal")]
  public static extern global::System.IntPtr Ocean_AddDecal(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, float jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_ScaleDecal")]
  public static extern void Ocean_ScaleDecal(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_MoveDecal")]
  public static extern void Ocean_MoveDecal(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_RotateDecal")]
  public static extern void Ocean_RotateDecal(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetDecalAlpha")]
  public static extern void Ocean_SetDecalAlpha(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_RemoveDecal")]
  public static extern void Ocean_RemoveDecal(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_0")]
  public static extern bool Ocean_GetHeight__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7, bool jarg8, bool jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, bool jarg11, global::System.Runtime.InteropServices.HandleRef jarg12);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_1")]
  public static extern bool Ocean_GetHeight__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7, bool jarg8, bool jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, bool jarg11);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_2")]
  public static extern bool Ocean_GetHeight__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7, bool jarg8, bool jarg9, global::System.Runtime.InteropServices.HandleRef jarg10);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_3")]
  public static extern bool Ocean_GetHeight__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7, bool jarg8, bool jarg9);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_4")]
  public static extern bool Ocean_GetHeight__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7, bool jarg8);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_5")]
  public static extern bool Ocean_GetHeight__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_6")]
  public static extern bool Ocean_GetHeight__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetHeight__SWIG_7")]
  public static extern bool Ocean_GetHeight__SWIG_7(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWavesIntersection__SWIG_0")]
  public static extern bool Ocean_GetWavesIntersection__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, double jarg6, bool jarg7, bool jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWavesIntersection__SWIG_1")]
  public static extern bool Ocean_GetWavesIntersection__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, double jarg6, bool jarg7, bool jarg8);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWavesIntersection__SWIG_2")]
  public static extern bool Ocean_GetWavesIntersection__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, double jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWavesIntersection__SWIG_3")]
  public static extern bool Ocean_GetWavesIntersection__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, double jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWavesIntersection__SWIG_4")]
  public static extern bool Ocean_GetWavesIntersection__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetIntersection__SWIG_0")]
  public static extern bool Ocean_GetIntersection__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetIntersection__SWIG_1")]
  public static extern bool Ocean_GetIntersection__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWaveHeading")]
  public static extern float Ocean_GetWaveHeading(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_EnableSpray")]
  public static extern void Ocean_EnableSpray(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SprayEnabled")]
  public static extern bool Ocean_SprayEnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetRefractionColor")]
  public static extern void Ocean_SetRefractionColor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetRefractionColor")]
  public static extern global::System.IntPtr Ocean_GetRefractionColor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetReflectionScale")]
  public static extern void Ocean_SetReflectionScale(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetReflectionScale")]
  public static extern float Ocean_GetReflectionScale(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetPlanarReflectionBlend")]
  public static extern void Ocean_SetPlanarReflectionBlend(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetPlanarReflectionBlend")]
  public static extern float Ocean_GetPlanarReflectionBlend(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_ComputeReflectionMatrices__SWIG_0")]
  public static extern bool Ocean_ComputeReflectionMatrices__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_ComputeReflectionMatrices__SWIG_1")]
  public static extern bool Ocean_ComputeReflectionMatrices__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetEnvironment")]
  public static extern global::System.IntPtr Ocean_GetEnvironment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_IsCameraAboveWater__SWIG_0")]
  public static extern bool Ocean_IsCameraAboveWater__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_IsCameraAboveWater__SWIG_1")]
  public static extern bool Ocean_IsCameraAboveWater__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetDepthOffset")]
  public static extern void Ocean_SetDepthOffset(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetDepthOffset")]
  public static extern float Ocean_GetDepthOffset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetDisplacementDampingDistance")]
  public static extern void Ocean_SetDisplacementDampingDistance(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetDisplacementDampingDistance")]
  public static extern double Ocean_GetDisplacementDampingDistance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_EnableGodRays")]
  public static extern void Ocean_EnableGodRays(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GodRaysEnabled")]
  public static extern bool Ocean_GodRaysEnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetGodRaysFade")]
  public static extern void Ocean_SetGodRaysFade(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetGodRaysFade")]
  public static extern float Ocean_GetGodRaysFade(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Lock")]
  public static extern void Ocean_Lock(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_Unlock")]
  public static extern void Ocean_Unlock(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetQuality")]
  public static extern void Ocean_SetQuality(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetQuality")]
  public static extern int Ocean_GetQuality(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetLinearColorSpace")]
  public static extern void Ocean_SetLinearColorSpace(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetLinearColorSpace")]
  public static extern bool Ocean_GetLinearColorSpace(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetMaximumWavePeriod")]
  public static extern void Ocean_SetMaximumWavePeriod(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetMaximumWavePeriod")]
  public static extern double Ocean_GetMaximumWavePeriod(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetClipDistances")]
  public static extern void Ocean_SetClipDistances(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetClipDistances")]
  public static extern void Ocean_GetClipDistances(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_OverrideFFTInputArray")]
  public static extern bool Ocean_OverrideFFTInputArray(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_ClearFFTInputArray")]
  public static extern void Ocean_ClearFFTInputArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetFFTInputArray")]
  public static extern global::System.IntPtr Ocean_GetFFTInputArray(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetRotorWashUseDecals")]
  public static extern void Ocean_SetRotorWashUseDecals(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetRotorWashUseDecals")]
  public static extern bool Ocean_GetRotorWashUseDecals(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_SetWaterModel")]
  public static extern void Ocean_SetWaterModel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Ocean_GetWaterModel")]
  public static extern int Ocean_GetWaterModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Ocean")]
  public static extern global::System.IntPtr new_Ocean();
}

}
