//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class TritonEnvironment {
  public static SWIGTYPE_p_double new_double_array(int nelements) {
    global::System.IntPtr cPtr = TritonEnvironmentPINVOKE.new_double_array(nelements);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public static void delete_double_array(SWIGTYPE_p_double ary) {
    TritonEnvironmentPINVOKE.delete_double_array(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double double_array_getitem(SWIGTYPE_p_double ary, int index) {
    double ret = TritonEnvironmentPINVOKE.double_array_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
    return ret;
  }

  public static void double_array_setitem(SWIGTYPE_p_double ary, int index, double value) {
    TritonEnvironmentPINVOKE.double_array_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}

}
