//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

class TritonWakeGeneratorPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionCallbacks_TritonWakeGenerator")]
    public static extern void SWIGRegisterExceptionCallbacks_TritonWakeGenerator(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_TritonWakeGenerator")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_TritonWakeGenerator(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_TritonWakeGenerator(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_TritonWakeGenerator(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterStringCallback_TritonWakeGenerator")]
    public static extern void SWIGRegisterStringCallback_TritonWakeGenerator(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_TritonWakeGenerator(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static TritonWakeGeneratorPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_numSprays_set")]
  public static extern void SBowSprayEmitter_numSprays_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_numSprays_get")]
  public static extern int SBowSprayEmitter_numSprays_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_offset_set")]
  public static extern void SBowSprayEmitter_offset_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_offset_get")]
  public static extern global::System.IntPtr SBowSprayEmitter_offset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_sprayVelocityScale_set")]
  public static extern void SBowSprayEmitter_sprayVelocityScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_sprayVelocityScale_get")]
  public static extern double SBowSprayEmitter_sprayVelocityScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_spraySizeScale_set")]
  public static extern void SBowSprayEmitter_spraySizeScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SBowSprayEmitter_spraySizeScale_get")]
  public static extern double SBowSprayEmitter_spraySizeScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_SBowSprayEmitter")]
  public static extern global::System.IntPtr new_SBowSprayEmitter(int jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_SBowSprayEmitter")]
  public static extern void delete_SBowSprayEmitter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_WakeGeneratorParameters")]
  public static extern global::System.IntPtr new_WakeGeneratorParameters();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_WakeGeneratorParameters")]
  public static extern void delete_WakeGeneratorParameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sprayEffects_set")]
  public static extern void WakeGeneratorParameters_sprayEffects_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sprayEffects_get")]
  public static extern bool WakeGeneratorParameters_sprayEffects_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSprayOffset_set")]
  public static extern void WakeGeneratorParameters_bowSprayOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSprayOffset_get")]
  public static extern double WakeGeneratorParameters_bowSprayOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSprayEmitters_set")]
  public static extern void WakeGeneratorParameters_bowSprayEmitters_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSprayEmitters_get")]
  public static extern global::System.IntPtr WakeGeneratorParameters_bowSprayEmitters_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWave_set")]
  public static extern void WakeGeneratorParameters_bowWave_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWave_get")]
  public static extern bool WakeGeneratorParameters_bowWave_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveOffset_set")]
  public static extern void WakeGeneratorParameters_bowWaveOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveOffset_get")]
  public static extern double WakeGeneratorParameters_bowWaveOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveScale_set")]
  public static extern void WakeGeneratorParameters_bowWaveScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveScale_get")]
  public static extern double WakeGeneratorParameters_bowWaveScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveMax_set")]
  public static extern void WakeGeneratorParameters_bowWaveMax_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWaveMax_get")]
  public static extern double WakeGeneratorParameters_bowWaveMax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSize_set")]
  public static extern void WakeGeneratorParameters_bowSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowSize_get")]
  public static extern double WakeGeneratorParameters_bowSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWaves_set")]
  public static extern void WakeGeneratorParameters_sternWaves_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWaves_get")]
  public static extern bool WakeGeneratorParameters_sternWaves_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWaveOffset_set")]
  public static extern void WakeGeneratorParameters_sternWaveOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWaveOffset_get")]
  public static extern double WakeGeneratorParameters_sternWaveOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_length_set")]
  public static extern void WakeGeneratorParameters_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_length_get")]
  public static extern double WakeGeneratorParameters_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_beamWidth_set")]
  public static extern void WakeGeneratorParameters_beamWidth_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_beamWidth_get")]
  public static extern double WakeGeneratorParameters_beamWidth_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_draft_set")]
  public static extern void WakeGeneratorParameters_draft_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_draft_get")]
  public static extern double WakeGeneratorParameters_draft_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWash_set")]
  public static extern void WakeGeneratorParameters_propWash_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWash_get")]
  public static extern bool WakeGeneratorParameters_propWash_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashOffset_set")]
  public static extern void WakeGeneratorParameters_propWashOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashOffset_get")]
  public static extern double WakeGeneratorParameters_propWashOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashWidthMultiplier_set")]
  public static extern void WakeGeneratorParameters_propWashWidthMultiplier_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashWidthMultiplier_get")]
  public static extern double WakeGeneratorParameters_propWashWidthMultiplier_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashFadeTime_set")]
  public static extern void WakeGeneratorParameters_propWashFadeTime_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_propWashFadeTime_get")]
  public static extern double WakeGeneratorParameters_propWashFadeTime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_numHullSprays_set")]
  public static extern void WakeGeneratorParameters_numHullSprays_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_numHullSprays_get")]
  public static extern int WakeGeneratorParameters_numHullSprays_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayStartOffset_set")]
  public static extern void WakeGeneratorParameters_hullSprayStartOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayStartOffset_get")]
  public static extern double WakeGeneratorParameters_hullSprayStartOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayEndOffset_set")]
  public static extern void WakeGeneratorParameters_hullSprayEndOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayEndOffset_get")]
  public static extern double WakeGeneratorParameters_hullSprayEndOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayScale_set")]
  public static extern void WakeGeneratorParameters_hullSprayScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayScale_get")]
  public static extern double WakeGeneratorParameters_hullSprayScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSpraySizeScale_set")]
  public static extern void WakeGeneratorParameters_hullSpraySizeScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSpraySizeScale_get")]
  public static extern double WakeGeneratorParameters_hullSpraySizeScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayVerticalOffset_set")]
  public static extern void WakeGeneratorParameters_hullSprayVerticalOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullSprayVerticalOffset_get")]
  public static extern double WakeGeneratorParameters_hullSprayVerticalOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWakeMultiplier_set")]
  public static extern void WakeGeneratorParameters_bowWakeMultiplier_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_bowWakeMultiplier_get")]
  public static extern double WakeGeneratorParameters_bowWakeMultiplier_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWakeMultiplier_set")]
  public static extern void WakeGeneratorParameters_sternWakeMultiplier_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_sternWakeMultiplier_get")]
  public static extern double WakeGeneratorParameters_sternWakeMultiplier_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullWakeWidth_set")]
  public static extern void WakeGeneratorParameters_hullWakeWidth_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullWakeWidth_get")]
  public static extern float WakeGeneratorParameters_hullWakeWidth_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullWakeLength_set")]
  public static extern void WakeGeneratorParameters_hullWakeLength_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_hullWakeLength_get")]
  public static extern float WakeGeneratorParameters_hullWakeLength_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_shipSpeedMaxFoam_set")]
  public static extern void WakeGeneratorParameters_shipSpeedMaxFoam_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_shipSpeedMaxFoam_get")]
  public static extern float WakeGeneratorParameters_shipSpeedMaxFoam_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_shipSpeedMinFoam_set")]
  public static extern void WakeGeneratorParameters_shipSpeedMinFoam_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGeneratorParameters_shipSpeedMinFoam_get")]
  public static extern float WakeGeneratorParameters_shipSpeedMinFoam_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_WakeGenerator")]
  public static extern global::System.IntPtr new_WakeGenerator(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_WakeGenerator")]
  public static extern void delete_WakeGenerator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_Update__SWIG_0")]
  public static extern void WakeGenerator_Update__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, double jarg4, double jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_Update__SWIG_1")]
  public static extern void WakeGenerator_Update__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, double jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_ClearWakes")]
  public static extern void WakeGenerator_ClearWakes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetPosition")]
  public static extern global::System.IntPtr WakeGenerator_GetPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetSternPosition")]
  public static extern global::System.IntPtr WakeGenerator_GetSternPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetVelocity")]
  public static extern double WakeGenerator_GetVelocity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_HasPropWash")]
  public static extern bool WakeGenerator_HasPropWash(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_SetLODDistance")]
  public static extern void WakeGenerator_SetLODDistance(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetLODDistance")]
  public static extern double WakeGenerator_GetLODDistance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetParameters")]
  public static extern global::System.IntPtr WakeGenerator_GetParameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_SetParameters")]
  public static extern void WakeGenerator_SetParameters(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_OceanDestroyed")]
  public static extern void WakeGenerator_OceanDestroyed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_WakeManagerDestroyed")]
  public static extern void WakeGenerator_WakeManagerDestroyed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetMaxWakeNumber")]
  public static extern int WakeGenerator_GetMaxWakeNumber(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetDistanceTravelled")]
  public static extern double WakeGenerator_GetDistanceTravelled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WakeGenerator_GetOcean")]
  public static extern global::System.IntPtr WakeGenerator_GetOcean(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
