//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class TritonRotorWash {
  public static readonly int NUM_DECALS = TritonRotorWashPINVOKE.NUM_DECALS_get();
  public static readonly int SMOOTH_BUFFER_SIZE = TritonRotorWashPINVOKE.SMOOTH_BUFFER_SIZE_get();
}

}
