//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class TritonOcean {
  public static SWIGTYPE_p_float new_floatp() {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.new_floatp();
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_float copy_floatp(float value) {
    global::System.IntPtr cPtr = TritonOceanPINVOKE.copy_floatp(value);
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public static void delete_floatp(SWIGTYPE_p_float obj) {
    TritonOceanPINVOKE.delete_floatp(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static void floatp_assign(SWIGTYPE_p_float obj, float value) {
    TritonOceanPINVOKE.floatp_assign(SWIGTYPE_p_float.getCPtr(obj), value);
  }

  public static float floatp_value(SWIGTYPE_p_float obj) {
    float ret = TritonOceanPINVOKE.floatp_value(SWIGTYPE_p_float.getCPtr(obj));
    return ret;
  }

}

}
