//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

class TritonEnvironmentPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionCallbacks_TritonEnvironment")]
    public static extern void SWIGRegisterExceptionCallbacks_TritonEnvironment(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_TritonEnvironment")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_TritonEnvironment(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_TritonEnvironment(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_TritonEnvironment(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="SWIGRegisterStringCallback_TritonEnvironment")]
    public static extern void SWIGRegisterStringCallback_TritonEnvironment(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_TritonEnvironment(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static TritonEnvironmentPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_ResourceLoader__SWIG_0")]
  public static extern global::System.IntPtr new_ResourceLoader__SWIG_0(string jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_ResourceLoader__SWIG_1")]
  public static extern global::System.IntPtr new_ResourceLoader__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_ResourceLoader")]
  public static extern void delete_ResourceLoader(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ResourceLoader_SetResourceDirPath__SWIG_0")]
  public static extern void ResourceLoader_SetResourceDirPath__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ResourceLoader_SetResourceDirPath__SWIG_1")]
  public static extern void ResourceLoader_SetResourceDirPath__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ResourceLoader_GetResourceDirPath")]
  public static extern string ResourceLoader_GetResourceDirPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ResourceLoader_LoadResource")]
  public static extern bool ResourceLoader_LoadResource(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ResourceLoader_FreeResource")]
  public static extern void ResourceLoader_FreeResource(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_ScopedResource")]
  public static extern global::System.IntPtr new_ScopedResource(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_ScopedResource")]
  public static extern void delete_ScopedResource(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_ScopedResource_Data")]
  public static extern string ScopedResource_Data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_WindFetch")]
  public static extern global::System.IntPtr new_WindFetch();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_SetWind")]
  public static extern void WindFetch_SetWind(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_SetLocalization")]
  public static extern void WindFetch_SetLocalization(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_SetFetchLength")]
  public static extern void WindFetch_SetFetchLength(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_ClearLocalization")]
  public static extern void WindFetch_ClearLocalization(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_ClearFetchLength")]
  public static extern void WindFetch_ClearFetchLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_GetWindAtLocation")]
  public static extern void WindFetch_GetWindAtLocation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_WindFetch_AdjustForLeftHanded")]
  public static extern void WindFetch_AdjustForLeftHanded(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_WindFetch")]
  public static extern void delete_WindFetch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3__SWIG_0")]
  public static extern global::System.IntPtr new_Vector3__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3__SWIG_1")]
  public static extern global::System.IntPtr new_Vector3__SWIG_1(double jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3__SWIG_2")]
  public static extern global::System.IntPtr new_Vector3__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3__SWIG_3")]
  public static extern global::System.IntPtr new_Vector3__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Length")]
  public static extern double Vector3_Length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_SquaredLength")]
  public static extern double Vector3_SquaredLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Normalize")]
  public static extern void Vector3_Normalize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Dot")]
  public static extern double Vector3_Dot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Cross")]
  public static extern global::System.IntPtr Vector3_Cross(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Serialize")]
  public static extern void Vector3_Serialize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_Unserialize")]
  public static extern void Vector3_Unserialize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_x_set")]
  public static extern void Vector3_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_x_get")]
  public static extern double Vector3_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_y_set")]
  public static extern void Vector3_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_y_get")]
  public static extern double Vector3_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_z_set")]
  public static extern void Vector3_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3_z_get")]
  public static extern double Vector3_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Vector3")]
  public static extern void delete_Vector3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3f__SWIG_0")]
  public static extern global::System.IntPtr new_Vector3f__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3f__SWIG_1")]
  public static extern global::System.IntPtr new_Vector3f__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector3f__SWIG_2")]
  public static extern global::System.IntPtr new_Vector3f__SWIG_2(float jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_Length")]
  public static extern float Vector3f_Length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_Normalize")]
  public static extern void Vector3f_Normalize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_Dot")]
  public static extern double Vector3f_Dot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_x_set")]
  public static extern void Vector3f_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_x_get")]
  public static extern float Vector3f_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_y_set")]
  public static extern void Vector3f_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_y_get")]
  public static extern float Vector3f_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_z_set")]
  public static extern void Vector3f_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector3f_z_get")]
  public static extern float Vector3f_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Vector3f")]
  public static extern void delete_Vector3f(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_TBoundingBox__SWIG_0")]
  public static extern global::System.IntPtr new_TBoundingBox__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_TBoundingBox__SWIG_1")]
  public static extern global::System.IntPtr new_TBoundingBox__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_TBoundingBox__SWIG_2")]
  public static extern global::System.IntPtr new_TBoundingBox__SWIG_2(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TBoundingBox_Contains")]
  public static extern bool TBoundingBox_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TBoundingBox_m_vMin_set")]
  public static extern void TBoundingBox_m_vMin_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TBoundingBox_m_vMin_get")]
  public static extern global::System.IntPtr TBoundingBox_m_vMin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TBoundingBox_m_vMax_set")]
  public static extern void TBoundingBox_m_vMax_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_TBoundingBox_m_vMax_get")]
  public static extern global::System.IntPtr TBoundingBox_m_vMax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_TBoundingBox")]
  public static extern void delete_TBoundingBox(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_Identity_set")]
  public static extern void Matrix3_Identity_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_Identity_get")]
  public static extern global::System.IntPtr Matrix3_Identity_get();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix3__SWIG_0")]
  public static extern global::System.IntPtr new_Matrix3__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix3__SWIG_1")]
  public static extern global::System.IntPtr new_Matrix3__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix3__SWIG_2")]
  public static extern global::System.IntPtr new_Matrix3__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Matrix3")]
  public static extern void delete_Matrix3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_ToFloatArray")]
  public static extern void Matrix3_ToFloatArray(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_FromRx")]
  public static extern void Matrix3_FromRx(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_FromRy")]
  public static extern void Matrix3_FromRy(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_FromRz")]
  public static extern void Matrix3_FromRz(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_FromXYZ")]
  public static extern void Matrix3_FromXYZ(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_Transpose")]
  public static extern global::System.IntPtr Matrix3_Transpose(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_elem_set")]
  public static extern void Matrix3_elem_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix3_elem_get")]
  public static extern global::System.IntPtr Matrix3_elem_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector4__SWIG_0")]
  public static extern global::System.IntPtr new_Vector4__SWIG_0(double jarg1, double jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector4__SWIG_1")]
  public static extern global::System.IntPtr new_Vector4__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Vector4__SWIG_2")]
  public static extern global::System.IntPtr new_Vector4__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_Dot")]
  public static extern double Vector4_Dot(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_x_set")]
  public static extern void Vector4_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_x_get")]
  public static extern double Vector4_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_y_set")]
  public static extern void Vector4_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_y_get")]
  public static extern double Vector4_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_z_set")]
  public static extern void Vector4_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_z_get")]
  public static extern double Vector4_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_w_set")]
  public static extern void Vector4_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Vector4_w_get")]
  public static extern double Vector4_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Vector4")]
  public static extern void delete_Vector4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_Identity_set")]
  public static extern void Matrix4_Identity_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_Identity_get")]
  public static extern global::System.IntPtr Matrix4_Identity_get();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix4__SWIG_0")]
  public static extern global::System.IntPtr new_Matrix4__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix4__SWIG_1")]
  public static extern global::System.IntPtr new_Matrix4__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12, double jarg13, double jarg14, double jarg15, double jarg16);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Matrix4__SWIG_2")]
  public static extern global::System.IntPtr new_Matrix4__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Matrix4")]
  public static extern void delete_Matrix4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_ToFloatArray")]
  public static extern void Matrix4_ToFloatArray(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_Transpose")]
  public static extern void Matrix4_Transpose(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_InverseCramers__SWIG_0")]
  public static extern global::System.IntPtr Matrix4_InverseCramers__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_InverseCramers__SWIG_1")]
  public static extern global::System.IntPtr Matrix4_InverseCramers__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_GetRow")]
  public static extern global::System.IntPtr Matrix4_GetRow(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_elem_set")]
  public static extern void Matrix4_elem_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Matrix4_elem_get")]
  public static extern global::System.IntPtr Matrix4_elem_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_double_array")]
  public static extern global::System.IntPtr new_double_array(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_double_array")]
  public static extern void delete_double_array(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_double_array_getitem")]
  public static extern double double_array_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_double_array_setitem")]
  public static extern void double_array_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_HeightMapContainer")]
  public static extern global::System.IntPtr new_HeightMapContainer();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_HeightMapContainer")]
  public static extern void delete_HeightMapContainer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_HeightMapContainer_heightMap_set")]
  public static extern void HeightMapContainer_heightMap_set(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_HeightMapContainer_heightMap_get")]
  public static extern System.IntPtr HeightMapContainer_heightMap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_HeightMapContainer_heightMapMatrix_set")]
  public static extern void HeightMapContainer_heightMapMatrix_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_HeightMapContainer_heightMapMatrix_get")]
  public static extern global::System.IntPtr HeightMapContainer_heightMapMatrix_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_BreakingWavesParameters")]
  public static extern global::System.IntPtr new_BreakingWavesParameters();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetSteepness")]
  public static extern void BreakingWavesParameters_SetSteepness(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetWavelength")]
  public static extern void BreakingWavesParameters_SetWavelength(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetWavelengthVariance")]
  public static extern void BreakingWavesParameters_SetWavelengthVariance(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetWaveDirection")]
  public static extern void BreakingWavesParameters_SetWaveDirection(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetAutoWaveDirection")]
  public static extern void BreakingWavesParameters_SetAutoWaveDirection(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetAmplitude")]
  public static extern void BreakingWavesParameters_SetAmplitude(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetSurgeDepth")]
  public static extern void BreakingWavesParameters_SetSurgeDepth(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetSteepnessVariance")]
  public static extern void BreakingWavesParameters_SetSteepnessVariance(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_SetDepthFalloff")]
  public static extern void BreakingWavesParameters_SetDepthFalloff(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetSteepness")]
  public static extern float BreakingWavesParameters_GetSteepness(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetWavelength")]
  public static extern float BreakingWavesParameters_GetWavelength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetWavelengthVariance")]
  public static extern float BreakingWavesParameters_GetWavelengthVariance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetWaveDirection")]
  public static extern global::System.IntPtr BreakingWavesParameters_GetWaveDirection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetAmplitude")]
  public static extern float BreakingWavesParameters_GetAmplitude(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetSurgeDepth")]
  public static extern float BreakingWavesParameters_GetSurgeDepth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetSteepnessVariance")]
  public static extern float BreakingWavesParameters_GetSteepnessVariance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetPhaseConstant")]
  public static extern float BreakingWavesParameters_GetPhaseConstant(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetExpK")]
  public static extern float BreakingWavesParameters_GetExpK(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetSpeed")]
  public static extern float BreakingWavesParameters_GetSpeed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetAutoWaveDirection")]
  public static extern bool BreakingWavesParameters_GetAutoWaveDirection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_BreakingWavesParameters_GetDepthFalloff")]
  public static extern float BreakingWavesParameters_GetDepthFalloff(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_BreakingWavesParameters")]
  public static extern void delete_BreakingWavesParameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_wavelength_set")]
  public static extern void SwellDescription_wavelength_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_wavelength_get")]
  public static extern float SwellDescription_wavelength_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_height_set")]
  public static extern void SwellDescription_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_height_get")]
  public static extern float SwellDescription_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_direction_set")]
  public static extern void SwellDescription_direction_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_direction_get")]
  public static extern float SwellDescription_direction_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_phase_set")]
  public static extern void SwellDescription_phase_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_SwellDescription_phase_get")]
  public static extern float SwellDescription_phase_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_SwellDescription")]
  public static extern global::System.IntPtr new_SwellDescription();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_SwellDescription")]
  public static extern void delete_SwellDescription(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_new_Environment")]
  public static extern global::System.IntPtr new_Environment();

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_Initialize__SWIG_0")]
  public static extern int Environment_Initialize__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, System.IntPtr jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_Initialize__SWIG_1")]
  public static extern int Environment_Initialize__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, System.IntPtr jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_Initialize__SWIG_2")]
  public static extern int Environment_Initialize__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_delete_Environment")]
  public static extern void delete_Environment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetLicenseCode")]
  public static extern void Environment_SetLicenseCode(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetResourceLoader")]
  public static extern global::System.IntPtr Environment_GetResourceLoader(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetDevice")]
  public static extern System.IntPtr Environment_GetDevice(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetDirectionalLight")]
  public static extern void Environment_SetDirectionalLight(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetAmbientLight")]
  public static extern void Environment_SetAmbientLight(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetLightDirection")]
  public static extern global::System.IntPtr Environment_GetLightDirection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetDirectionalLightColor")]
  public static extern global::System.IntPtr Environment_GetDirectionalLightColor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetAmbientLightColor")]
  public static extern global::System.IntPtr Environment_GetAmbientLightColor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetEnvironmentMap__SWIG_0")]
  public static extern void Environment_SetEnvironmentMap__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetEnvironmentMap__SWIG_1")]
  public static extern void Environment_SetEnvironmentMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetEnvironmentMap")]
  public static extern System.IntPtr Environment_GetEnvironmentMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetEnvironmentMapMatrix")]
  public static extern global::System.IntPtr Environment_GetEnvironmentMapMatrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetHeightMap__SWIG_0")]
  public static extern void Environment_SetHeightMap__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, System.IntPtr jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetHeightMap__SWIG_1")]
  public static extern void Environment_SetHeightMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, System.IntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetHeightMap__SWIG_2")]
  public static extern void Environment_SetHeightMap__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMap__SWIG_0")]
  public static extern System.IntPtr Environment_GetHeightMap__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMap__SWIG_1")]
  public static extern System.IntPtr Environment_GetHeightMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMapMatrix__SWIG_0")]
  public static extern global::System.IntPtr Environment_GetHeightMapMatrix__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMapMatrix__SWIG_1")]
  public static extern global::System.IntPtr Environment_GetHeightMapMatrix__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetHeightMapRange")]
  public static extern void Environment_SetHeightMapRange(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetHeightMapOffset")]
  public static extern void Environment_SetHeightMapOffset(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMapRange")]
  public static extern float Environment_GetHeightMapRange(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHeightMapOffset")]
  public static extern float Environment_GetHeightMapOffset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetDepthMap")]
  public static extern void Environment_SetDepthMap(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetDepthMap")]
  public static extern System.IntPtr Environment_GetDepthMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetBreakingWavesParameters")]
  public static extern void Environment_SetBreakingWavesParameters(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetBreakingWavesParameters")]
  public static extern global::System.IntPtr Environment_GetBreakingWavesParameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetPlanarReflectionMap__SWIG_0")]
  public static extern void Environment_SetPlanarReflectionMap__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetPlanarReflectionMap__SWIG_1")]
  public static extern void Environment_SetPlanarReflectionMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetPlanarReflectionMap")]
  public static extern System.IntPtr Environment_GetPlanarReflectionMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetPlanarReflectionMapMatrix")]
  public static extern global::System.IntPtr Environment_GetPlanarReflectionMapMatrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetPlanarReflectionDisplacementScale")]
  public static extern float Environment_GetPlanarReflectionDisplacementScale(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SimulateSeaState__SWIG_0")]
  public static extern void Environment_SimulateSeaState__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SimulateSeaState__SWIG_1")]
  public static extern void Environment_SimulateSeaState__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_AddWindFetch__SWIG_0")]
  public static extern void Environment_AddWindFetch__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_AddWindFetch__SWIG_1")]
  public static extern void Environment_AddWindFetch__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_ClearWindFetches")]
  public static extern void Environment_ClearWindFetches(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_AddSwell__SWIG_0")]
  public static extern void Environment_AddSwell__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_AddSwell__SWIG_1")]
  public static extern void Environment_AddSwell__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_AddSwell__SWIG_2")]
  public static extern void Environment_AddSwell__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_ClearSwells")]
  public static extern void Environment_ClearSwells(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetDouglasSeaScale__SWIG_0")]
  public static extern void Environment_SetDouglasSeaScale__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3, int jarg4, float jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetDouglasSeaScale__SWIG_1")]
  public static extern void Environment_SetDouglasSeaScale__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3, int jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetWind")]
  public static extern void Environment_GetWind(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetSeaLevel")]
  public static extern void Environment_SetSeaLevel(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetSeaLevel")]
  public static extern double Environment_GetSeaLevel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetAboveWaterVisibility")]
  public static extern void Environment_SetAboveWaterVisibility(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetAboveWaterVisibility")]
  public static extern void Environment_GetAboveWaterVisibility(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetBelowWaterVisibility")]
  public static extern void Environment_SetBelowWaterVisibility(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetBelowWaterVisibility")]
  public static extern void Environment_GetBelowWaterVisibility(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetWaveBlendDepth")]
  public static extern void Environment_SetWaveBlendDepth(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetWaveBlendDepth")]
  public static extern double Environment_GetWaveBlendDepth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetSunIntensity")]
  public static extern void Environment_SetSunIntensity(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetSunIntensity")]
  public static extern float Environment_GetSunIntensity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetWorldUnits")]
  public static extern void Environment_SetWorldUnits(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetWorldUnits")]
  public static extern double Environment_GetWorldUnits(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetCoordinateSystem")]
  public static extern int Environment_GetCoordinateSystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_IsGeocentric")]
  public static extern bool Environment_IsGeocentric(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetRenderer")]
  public static extern int Environment_GetRenderer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_IsOpenGL")]
  public static extern bool Environment_IsOpenGL(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_IsDirectX")]
  public static extern bool Environment_IsDirectX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetCameraMatrix__SWIG_0")]
  public static extern void Environment_SetCameraMatrix__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetCameraMatrix__SWIG_1")]
  public static extern void Environment_SetCameraMatrix__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetProjectionMatrix")]
  public static extern void Environment_SetProjectionMatrix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetViewport")]
  public static extern void Environment_SetViewport(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetZoomLevel")]
  public static extern void Environment_SetZoomLevel(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetZoomLevel")]
  public static extern float Environment_GetZoomLevel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetUserDefinedVertString")]
  public static extern void Environment_SetUserDefinedVertString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetUserDefinedFragString")]
  public static extern void Environment_SetUserDefinedFragString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetUserDefinedVertString")]
  public static extern string Environment_GetUserDefinedVertString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetUserDefinedFragString")]
  public static extern string Environment_GetUserDefinedFragString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetViewport")]
  public static extern bool Environment_GetViewport(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetCamera__SWIG_0")]
  public static extern global::System.IntPtr Environment_GetCamera__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_CreateCamera")]
  public static extern global::System.IntPtr Environment_CreateCamera(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_DestroyCamera")]
  public static extern void Environment_DestroyCamera(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetCameraMatrix")]
  public static extern global::System.IntPtr Environment_GetCameraMatrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetProjectionMatrix")]
  public static extern global::System.IntPtr Environment_GetProjectionMatrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetCameraPosition")]
  public static extern global::System.IntPtr Environment_GetCameraPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetUpVector")]
  public static extern global::System.IntPtr Environment_GetUpVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetRightVector")]
  public static extern global::System.IntPtr Environment_GetRightVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetConfigOption")]
  public static extern void Environment_SetConfigOption(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetConfigOption")]
  public static extern string Environment_GetConfigOption(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_CullSphere")]
  public static extern bool Environment_CullSphere(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_CullOrientedBoundingBox")]
  public static extern bool Environment_CullOrientedBoundingBox(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetHDREnabled")]
  public static extern bool Environment_GetHDREnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_EnableOpenMP")]
  public static extern void Environment_EnableOpenMP(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetOpenMPEnabled")]
  public static extern bool Environment_GetOpenMPEnabled(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetMaximumWaveHeight")]
  public static extern float Environment_GetMaximumWaveHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetCurrent")]
  public static extern void Environment_SetCurrent(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetCurrent")]
  public static extern void Environment_GetCurrent(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_SetWaterTransparency")]
  public static extern void Environment_SetWaterTransparency(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_GetWaterTransparency")]
  public static extern float Environment_GetWaterTransparency(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_CreateOpenGLStream")]
  public static extern global::System.IntPtr Environment_CreateOpenGLStream(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_DestroyOpenGLStream")]
  public static extern void Environment_DestroyOpenGLStream(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_ExecuteOpenGLStream")]
  public static extern void Environment_ExecuteOpenGLStream(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("TritonDLL", EntryPoint="CSharp_Triton_Environment_ResetOpenGLStream")]
  public static extern void Environment_ResetOpenGLStream(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);
}

}
