//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Vector4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Vector4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Vector4 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vector4() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Vector4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector4(double px, double py, double pz, double pw) : this(TritonEnvironmentPINVOKE.new_Vector4__SWIG_0(px, py, pz, pw), true) {
  }

  public Vector4(Vector3 v3) : this(TritonEnvironmentPINVOKE.new_Vector4__SWIG_1(Vector3.getCPtr(v3)), true) {
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector4() : this(TritonEnvironmentPINVOKE.new_Vector4__SWIG_2(), true) {
  }

  public double Dot(Vector4 v) {
    double ret = TritonEnvironmentPINVOKE.Vector4_Dot(swigCPtr, Vector4.getCPtr(v));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double x {
    set {
      TritonEnvironmentPINVOKE.Vector4_x_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector4_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      TritonEnvironmentPINVOKE.Vector4_y_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector4_y_get(swigCPtr);
      return ret;
    } 
  }

  public double z {
    set {
      TritonEnvironmentPINVOKE.Vector4_z_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector4_z_get(swigCPtr);
      return ret;
    } 
  }

  public double w {
    set {
      TritonEnvironmentPINVOKE.Vector4_w_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector4_w_get(swigCPtr);
      return ret;
    } 
  }

}

}
