//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Vector3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Vector3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Vector3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vector3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Vector3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector3() : this(TritonEnvironmentPINVOKE.new_Vector3__SWIG_0(), true) {
  }

  public Vector3(double px, double py, double pz) : this(TritonEnvironmentPINVOKE.new_Vector3__SWIG_1(px, py, pz), true) {
  }

  public Vector3(SWIGTYPE_p_double p) : this(TritonEnvironmentPINVOKE.new_Vector3__SWIG_2(SWIGTYPE_p_double.getCPtr(p)), true) {
  }

  public Vector3(Vector3 v) : this(TritonEnvironmentPINVOKE.new_Vector3__SWIG_3(Vector3.getCPtr(v)), true) {
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public double Length() {
    double ret = TritonEnvironmentPINVOKE.Vector3_Length(swigCPtr);
    return ret;
  }

  public double SquaredLength() {
    double ret = TritonEnvironmentPINVOKE.Vector3_SquaredLength(swigCPtr);
    return ret;
  }

  public void Normalize() {
    TritonEnvironmentPINVOKE.Vector3_Normalize(swigCPtr);
  }

  public double Dot(Vector3 v) {
    double ret = TritonEnvironmentPINVOKE.Vector3_Dot(swigCPtr, Vector3.getCPtr(v));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3 Cross(Vector3 v) {
    Vector3 ret = new Vector3(TritonEnvironmentPINVOKE.Vector3_Cross(swigCPtr, Vector3.getCPtr(v)), true);
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Serialize(SWIGTYPE_p_std__ostream s) {
    TritonEnvironmentPINVOKE.Vector3_Serialize(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(s));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Unserialize(SWIGTYPE_p_std__istream s) {
    TritonEnvironmentPINVOKE.Vector3_Unserialize(swigCPtr, SWIGTYPE_p_std__istream.getCPtr(s));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public double x {
    set {
      TritonEnvironmentPINVOKE.Vector3_x_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector3_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      TritonEnvironmentPINVOKE.Vector3_y_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector3_y_get(swigCPtr);
      return ret;
    } 
  }

  public double z {
    set {
      TritonEnvironmentPINVOKE.Vector3_z_set(swigCPtr, value);
    } 
    get {
      double ret = TritonEnvironmentPINVOKE.Vector3_z_get(swigCPtr);
      return ret;
    } 
  }

}

}
