//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class Vector3f : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public Vector3f(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector3f obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(Vector3f obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vector3f() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_Vector3f(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector3f() : this(TritonEnvironmentPINVOKE.new_Vector3f__SWIG_0(), true) {
  }

  public Vector3f(Vector3 v) : this(TritonEnvironmentPINVOKE.new_Vector3f__SWIG_1(Vector3.getCPtr(v)), true) {
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3f(float px, float py, float pz) : this(TritonEnvironmentPINVOKE.new_Vector3f__SWIG_2(px, py, pz), true) {
  }

  public float Length() {
    float ret = TritonEnvironmentPINVOKE.Vector3f_Length(swigCPtr);
    return ret;
  }

  public void Normalize() {
    TritonEnvironmentPINVOKE.Vector3f_Normalize(swigCPtr);
  }

  public double Dot(Vector3f v) {
    double ret = TritonEnvironmentPINVOKE.Vector3f_Dot(swigCPtr, Vector3f.getCPtr(v));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float x {
    set {
      TritonEnvironmentPINVOKE.Vector3f_x_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.Vector3f_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      TritonEnvironmentPINVOKE.Vector3f_y_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.Vector3f_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      TritonEnvironmentPINVOKE.Vector3f_z_set(swigCPtr, value);
    } 
    get {
      float ret = TritonEnvironmentPINVOKE.Vector3f_z_get(swigCPtr);
      return ret;
    } 
  }

}

}
