//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class WakeGenerator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public WakeGenerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(WakeGenerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(WakeGenerator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WakeGenerator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonWakeGeneratorPINVOKE.delete_WakeGenerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WakeGenerator(Ocean pOcean, WakeGeneratorParameters parameters) : this(TritonWakeGeneratorPINVOKE.new_WakeGenerator(Ocean.getCPtr(pOcean), WakeGeneratorParameters.getCPtr(parameters)), true) {
    if (TritonWakeGeneratorPINVOKE.SWIGPendingException.Pending) throw TritonWakeGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Update(Vector3 pPosition, Vector3 pDirection, double pVelocity, double pTime, bool pDisableWash) {
    TritonWakeGeneratorPINVOKE.WakeGenerator_Update__SWIG_0(swigCPtr, Vector3.getCPtr(pPosition), Vector3.getCPtr(pDirection), pVelocity, pTime, pDisableWash);
    if (TritonWakeGeneratorPINVOKE.SWIGPendingException.Pending) throw TritonWakeGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Update(Vector3 pPosition, Vector3 pDirection, double pVelocity, double pTime) {
    TritonWakeGeneratorPINVOKE.WakeGenerator_Update__SWIG_1(swigCPtr, Vector3.getCPtr(pPosition), Vector3.getCPtr(pDirection), pVelocity, pTime);
    if (TritonWakeGeneratorPINVOKE.SWIGPendingException.Pending) throw TritonWakeGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ClearWakes() {
    TritonWakeGeneratorPINVOKE.WakeGenerator_ClearWakes(swigCPtr);
  }

  public Vector3 GetPosition() {
    Vector3 ret = new Vector3(TritonWakeGeneratorPINVOKE.WakeGenerator_GetPosition(swigCPtr), true);
    return ret;
  }

  public Vector3 GetSternPosition() {
    Vector3 ret = new Vector3(TritonWakeGeneratorPINVOKE.WakeGenerator_GetSternPosition(swigCPtr), true);
    return ret;
  }

  public double GetVelocity() {
    double ret = TritonWakeGeneratorPINVOKE.WakeGenerator_GetVelocity(swigCPtr);
    return ret;
  }

  public bool HasPropWash() {
    bool ret = TritonWakeGeneratorPINVOKE.WakeGenerator_HasPropWash(swigCPtr);
    return ret;
  }

  public void SetLODDistance(double distance) {
    TritonWakeGeneratorPINVOKE.WakeGenerator_SetLODDistance(swigCPtr, distance);
  }

  public double GetLODDistance() {
    double ret = TritonWakeGeneratorPINVOKE.WakeGenerator_GetLODDistance(swigCPtr);
    return ret;
  }

  public WakeGeneratorParameters GetParameters() {
    WakeGeneratorParameters ret = new WakeGeneratorParameters(TritonWakeGeneratorPINVOKE.WakeGenerator_GetParameters(swigCPtr), false);
    return ret;
  }

  public void SetParameters(WakeGeneratorParameters parameters) {
    TritonWakeGeneratorPINVOKE.WakeGenerator_SetParameters(swigCPtr, WakeGeneratorParameters.getCPtr(parameters));
    if (TritonWakeGeneratorPINVOKE.SWIGPendingException.Pending) throw TritonWakeGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void OceanDestroyed() {
    TritonWakeGeneratorPINVOKE.WakeGenerator_OceanDestroyed(swigCPtr);
  }

  public void WakeManagerDestroyed() {
    TritonWakeGeneratorPINVOKE.WakeGenerator_WakeManagerDestroyed(swigCPtr);
  }

  public int GetMaxWakeNumber() {
    int ret = TritonWakeGeneratorPINVOKE.WakeGenerator_GetMaxWakeNumber(swigCPtr);
    return ret;
  }

  public double GetDistanceTravelled() {
    double ret = TritonWakeGeneratorPINVOKE.WakeGenerator_GetDistanceTravelled(swigCPtr);
    return ret;
  }

  public Ocean GetOcean() {
    global::System.IntPtr cPtr = TritonWakeGeneratorPINVOKE.WakeGenerator_GetOcean(swigCPtr);
    Ocean ret = (cPtr == global::System.IntPtr.Zero) ? null : new Ocean(cPtr, false);
    return ret;
  }

}

}
