//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class WakeGeneratorParameters : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public WakeGeneratorParameters(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(WakeGeneratorParameters obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(WakeGeneratorParameters obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WakeGeneratorParameters() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonWakeGeneratorPINVOKE.delete_WakeGeneratorParameters(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WakeGeneratorParameters() : this(TritonWakeGeneratorPINVOKE.new_WakeGeneratorParameters(), true) {
  }

  public bool sprayEffects {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sprayEffects_set(swigCPtr, value);
    } 
    get {
      bool ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sprayEffects_get(swigCPtr);
      return ret;
    } 
  }

  public double bowSprayOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSprayOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSprayOffset_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_Triton__SBowSprayEmitter_t bowSprayEmitters {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSprayEmitters_set(swigCPtr, SWIGTYPE_p_std__vectorT_Triton__SBowSprayEmitter_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSprayEmitters_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_Triton__SBowSprayEmitter_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_Triton__SBowSprayEmitter_t(cPtr, false);
      return ret;
    } 
  }

  public bool bowWave {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWave_set(swigCPtr, value);
    } 
    get {
      bool ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWave_get(swigCPtr);
      return ret;
    } 
  }

  public double bowWaveOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double bowWaveScale {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveScale_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveScale_get(swigCPtr);
      return ret;
    } 
  }

  public double bowWaveMax {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveMax_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWaveMax_get(swigCPtr);
      return ret;
    } 
  }

  public double bowSize {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSize_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowSize_get(swigCPtr);
      return ret;
    } 
  }

  public bool sternWaves {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWaves_set(swigCPtr, value);
    } 
    get {
      bool ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWaves_get(swigCPtr);
      return ret;
    } 
  }

  public double sternWaveOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWaveOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWaveOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double length {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_length_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_length_get(swigCPtr);
      return ret;
    } 
  }

  public double beamWidth {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_beamWidth_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_beamWidth_get(swigCPtr);
      return ret;
    } 
  }

  public double draft {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_draft_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_draft_get(swigCPtr);
      return ret;
    } 
  }

  public bool propWash {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWash_set(swigCPtr, value);
    } 
    get {
      bool ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWash_get(swigCPtr);
      return ret;
    } 
  }

  public double propWashOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double propWashWidthMultiplier {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashWidthMultiplier_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashWidthMultiplier_get(swigCPtr);
      return ret;
    } 
  }

  public double propWashFadeTime {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashFadeTime_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_propWashFadeTime_get(swigCPtr);
      return ret;
    } 
  }

  public int numHullSprays {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_numHullSprays_set(swigCPtr, value);
    } 
    get {
      int ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_numHullSprays_get(swigCPtr);
      return ret;
    } 
  }

  public double hullSprayStartOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayStartOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayStartOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double hullSprayEndOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayEndOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayEndOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double hullSprayScale {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayScale_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayScale_get(swigCPtr);
      return ret;
    } 
  }

  public double hullSpraySizeScale {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSpraySizeScale_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSpraySizeScale_get(swigCPtr);
      return ret;
    } 
  }

  public double hullSprayVerticalOffset {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayVerticalOffset_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullSprayVerticalOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double bowWakeMultiplier {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWakeMultiplier_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_bowWakeMultiplier_get(swigCPtr);
      return ret;
    } 
  }

  public double sternWakeMultiplier {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWakeMultiplier_set(swigCPtr, value);
    } 
    get {
      double ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_sternWakeMultiplier_get(swigCPtr);
      return ret;
    } 
  }

  public float hullWakeWidth {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullWakeWidth_set(swigCPtr, value);
    } 
    get {
      float ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullWakeWidth_get(swigCPtr);
      return ret;
    } 
  }

  public float hullWakeLength {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullWakeLength_set(swigCPtr, value);
    } 
    get {
      float ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_hullWakeLength_get(swigCPtr);
      return ret;
    } 
  }

  public float shipSpeedMaxFoam {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_shipSpeedMaxFoam_set(swigCPtr, value);
    } 
    get {
      float ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_shipSpeedMaxFoam_get(swigCPtr);
      return ret;
    } 
  }

  public float shipSpeedMinFoam {
    set {
      TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_shipSpeedMinFoam_set(swigCPtr, value);
    } 
    get {
      float ret = TritonWakeGeneratorPINVOKE.WakeGeneratorParameters_shipSpeedMinFoam_get(swigCPtr);
      return ret;
    } 
  }

}

}
