//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Triton {

public class WindFetch : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public WindFetch(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(WindFetch obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(WindFetch obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~WindFetch() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TritonEnvironmentPINVOKE.delete_WindFetch(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public WindFetch() : this(TritonEnvironmentPINVOKE.new_WindFetch(), true) {
  }

  public void SetWind(double speed, double direction) {
    TritonEnvironmentPINVOKE.WindFetch_SetWind(swigCPtr, speed, direction);
  }

  public void SetLocalization(SWIGTYPE_p_Vector3 center, SWIGTYPE_p_Vector3 radii) {
    TritonEnvironmentPINVOKE.WindFetch_SetLocalization(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(center), SWIGTYPE_p_Vector3.getCPtr(radii));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetFetchLength(double fetch) {
    TritonEnvironmentPINVOKE.WindFetch_SetFetchLength(swigCPtr, fetch);
  }

  public void ClearLocalization() {
    TritonEnvironmentPINVOKE.WindFetch_ClearLocalization(swigCPtr);
  }

  public void ClearFetchLength() {
    TritonEnvironmentPINVOKE.WindFetch_ClearFetchLength(swigCPtr);
  }

  public void GetWindAtLocation(SWIGTYPE_p_Vector3 position, SWIGTYPE_p_double windSpeed, SWIGTYPE_p_double windDirection, SWIGTYPE_p_double fetchLength) {
    TritonEnvironmentPINVOKE.WindFetch_GetWindAtLocation(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(position), SWIGTYPE_p_double.getCPtr(windSpeed), SWIGTYPE_p_double.getCPtr(windDirection), SWIGTYPE_p_double.getCPtr(fetchLength));
    if (TritonEnvironmentPINVOKE.SWIGPendingException.Pending) throw TritonEnvironmentPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AdjustForLeftHanded() {
    TritonEnvironmentPINVOKE.WindFetch_AdjustForLeftHanded(swigCPtr);
  }

}

}
